insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Mekele', 'Ethiopia', 'Carberry', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (71, 'São João dos Patos', 'Brazil', 'Jana', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (434, 'Pakenjeng', 'Indonesia', 'Lakewood Gardens', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Ocongate', 'Peru', 'Sachs', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (680, 'Sabbah', 'Syria', 'Esker', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (667, 'Brikama Nding', 'Gambia', 'Westport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (835, 'Farsta', 'Sweden', 'Washington', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (922, 'Puan', 'Argentina', 'Summerview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (7, 'Xarrë', 'Albania', 'Wayridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (452, 'Deranitan', 'Indonesia', 'Schurz', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Frontignan', 'France', 'Sunbrook', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (481, 'Bechlín', 'Czech Republic', 'Hoepker', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (376, 'Mache', 'Peru', 'Vahlen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (665, 'Eksjö', 'Sweden', 'Anthes', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (993, 'Suita', 'Japan', 'Sachtjen', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (996, 'Serh', 'China', 'Prentice', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (651, 'Dagou', 'China', 'Bashford', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (299, 'Hita', 'Japan', 'Cherokee', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (153, 'Chengnan', 'China', 'Lien', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (190, 'Kumalarang', 'Philippines', 'Tennyson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (645, 'Takanosu', 'Japan', 'Reindahl', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (676, 'Novi Itebej', 'Serbia', 'Garrison', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (360, 'Anicuns', 'Brazil', 'Superior', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (401, 'Daeosin Satu', 'Indonesia', 'Kim', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (646, 'Cirangrang', 'Indonesia', 'Annamark', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (519, 'Changsheng', 'China', 'Walton', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (796, 'Pakis', 'Indonesia', 'Heffernan', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (591, 'Nancy', 'France', 'Autumn Leaf', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (142, 'Malabar', 'Indonesia', 'Evergreen', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (319, 'Pancoran', 'Indonesia', 'Anderson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (432, 'Liangkou', 'China', 'Prairie Rose', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (870, 'Badu', 'China', 'Moose', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (80, 'Codajás', 'Brazil', 'Anhalt', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (228, 'Annecy', 'France', 'Menomonie', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (700, 'Hannō', 'Japan', 'Little Fleur', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (658, 'Maqian', 'China', 'Eagan', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (868, 'Xukou', 'China', 'Ohio', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Pringgabaya', 'Indonesia', 'Westport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (36, 'Costa Nova do Prado', 'Portugal', 'Mcguire', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (99, 'Nularan', 'Indonesia', 'Victoria', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Dulles', 'United States', 'Continental', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (421, 'Marneuli', 'Georgia', 'Beilfuss', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (935, 'Ngozi', 'Burundi', 'Bluestem', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (880, 'Uppsala', 'Sweden', 'Declaration', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (927, 'Fresno', 'United States', 'Pond', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (108, 'Xibing', 'China', 'Hauk', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Larnaca', 'Cyprus', 'Quincy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (465, 'Verkhnya Rozhanka', 'Ukraine', 'Northridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (938, 'Lenger', 'Kazakhstan', 'Spohn', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (337, 'Zarechnyy', 'Russia', 'Blaine', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (852, 'Kolape', 'Philippines', 'Carpenter', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (201, 'Áno Kalentíni', 'Greece', 'Thompson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (329, 'Simuay', 'Philippines', 'Cascade', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (850, 'Tippi', 'Ethiopia', 'Scott', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (603, 'Torzhok', 'Russia', 'Menomonie', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (809, 'Al Farwānīyah', 'Kuwait', 'Eastwood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (486, 'Las Varas', 'Argentina', 'Beilfuss', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (214, 'Barrio San Luis', 'Colombia', 'Mariners Cove', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (536, 'Vokhaïkó', 'Greece', 'Montana', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (669, 'Milówka', 'Poland', 'Westport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (525, 'Raci Kulon', 'Indonesia', 'Mesta', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (9, 'Cavaillon', 'France', 'Bowman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (940, 'Tangnan', 'China', 'Delladonna', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (420, 'Acobamba', 'Peru', 'Talisman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (267, 'Przyborów', 'Poland', 'Mayfield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (313, 'Tartaro', 'Philippines', 'Novick', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (474, 'Hodkovičky', 'Czech Republic', 'Tony', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (318, 'Lamas', 'Portugal', 'Logan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (290, 'Aduo', 'China', 'Cottonwood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (200, 'Tangtu', 'China', 'Lien', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (596, 'Ujiie', 'Japan', 'Dakota', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (728, 'München', 'Germany', 'Debs', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (317, 'Azua', 'Dominican Republic', 'Kensington', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (162, 'Al Ḩashwah', 'Yemen', 'Warrior', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (929, 'Molo', 'Kenya', 'Pankratz', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (686, 'Tetyushi', 'Russia', 'Anzinger', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (370, 'Dindima', 'Nigeria', 'Old Shore', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (580, 'Narong', 'China', 'Commercial', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (962, 'Nong Chik', 'Thailand', 'Garrison', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Kaoma', 'Zambia', 'Crescent Oaks', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (872, 'Mangkon Daja', 'Indonesia', 'Annamark', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (204, 'Lafayette', 'United States', 'Stone Corner', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (983, 'Sherbrooke', 'Canada', 'Lakewood Gardens', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (504, 'Lazaro Cardenas', 'Mexico', 'Scoville', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (18, 'Petrozavodsk', 'Russia', 'Pankratz', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (840, 'Pangligaran', 'Indonesia', 'Eagan', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (631, 'Hisings Kärra', 'Sweden', 'Bayside', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (861, 'Banjar Mambalkajanan', 'Indonesia', 'Orin', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (696, 'Beiqiao', 'China', 'Towne', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (472, 'Jevíčko', 'Czech Republic', 'Dunning', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (86, 'Hougong', 'China', 'Cherokee', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (433, 'Owerri', 'Nigeria', 'Esker', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (373, 'Ouzini', 'Comoros', 'Daystar', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (780, 'Cachachi', 'Peru', 'Ruskin', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (498, 'Karangora', 'Indonesia', 'Jackson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (547, 'Anoek', 'Indonesia', 'Ilene', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (418, 'Guradog', 'Indonesia', 'Rockefeller', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (117, 'Rancakuya', 'Indonesia', 'Maryland', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (550, 'Rogongon', 'Philippines', 'Sunfield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (874, 'Limbaži', 'Latvia', 'Burning Wood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (241, 'Masalovka', 'Russia', 'Merchant', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (463, 'Espinosa', 'Brazil', 'Fuller', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (460, 'Liulin', 'China', 'Eagan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (941, 'Aiánteio', 'Greece', 'Hoffman', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (43, 'Mayong', 'Indonesia', 'Shelley', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (718, 'Anadia', 'Portugal', 'Jenna', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (273, 'Cilentung', 'Indonesia', 'Sutherland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (284, 'Vatutino', 'Russia', 'South', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (24, 'Conima', 'Peru', 'Thackeray', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (519, 'Aubergenville', 'France', 'Lakeland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (618, 'Maluanluan', 'Philippines', 'Aberg', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (461, 'Vesoul', 'France', 'Main', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (287, 'Changsha', 'China', 'Lunder', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (179, 'Santa Venera', 'Malta', 'Sachtjen', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (449, 'Semang', 'Indonesia', 'Meadow Vale', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (605, 'Geji', 'China', 'Warner', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Litibakul', 'Indonesia', 'Northport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (678, 'Changgucheng', 'China', 'Merrick', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (90, 'Kebon', 'Indonesia', 'Scofield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (894, 'Pavshino', 'Russia', 'Northport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (489, 'Cartagena del Chairá', 'Colombia', 'Montana', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (889, 'Salgado', 'Brazil', 'Vahlen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (878, 'Timaru', 'New Zealand', 'Ridge Oak', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (908, 'Mingjiu', 'China', 'Nelson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (235, 'Centre de Flacq', 'Mauritius', 'Kim', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (419, 'Guanqing', 'China', 'Loeprich', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (86, 'Atyrau', 'Kazakhstan', 'Banding', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (295, 'Panalanoy', 'Philippines', 'La Follette', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (912, 'Phunphin', 'Thailand', 'Memorial', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (447, 'Могила', 'Macedonia', 'Northview', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (585, 'Dongfu', 'China', 'Sutteridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (218, 'Krzęcin', 'Poland', 'Kinsman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (55, 'Aimadamodo', 'Indonesia', 'Eagan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (182, 'Amiens', 'France', 'Lindbergh', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (344, 'La Asunción', 'Costa Rica', 'Rowland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Hohoe', 'Ghana', 'Del Sol', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (87, 'Athi River', 'Kenya', 'Village', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (945, 'Betaf', 'Indonesia', 'Comanche', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (849, 'Pasirmukti', 'Indonesia', 'Becker', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (862, 'Citeureup', 'Indonesia', 'Manufacturers', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (654, 'Boguszów-Gorce', 'Poland', 'Montana', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (441, 'Ndélé', 'Central African Republic', 'Brickson Park', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (794, 'Quyangqiao', 'China', 'Montana', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (198, 'Lazi', 'Ukraine', 'Farragut', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (919, 'Betzdorf', 'Luxembourg', 'Lighthouse Bay', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (735, 'Tayabamba', 'Peru', 'Division', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (70, 'Chenfang', 'China', 'Merry', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (70, 'Miguel Hidalgo', 'Mexico', 'Village', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (626, 'Les Coteaux', 'Canada', 'Vera', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (937, 'Boquira', 'Brazil', 'Gina', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (947, 'Shache', 'China', 'Northview', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (1000, 'San Martín', 'Argentina', '6th', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (438, 'Wangkung', 'Indonesia', 'Doe Crossing', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (493, 'Hlybokaye', 'Belarus', 'Esch', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (570, 'Cergy-Pontoise', 'France', 'Manley', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (171, 'Sagrada Familia', 'Philippines', 'Tony', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (416, 'Putrajaya', 'Malaysia', 'Michigan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (353, 'Terenozek', 'Kazakhstan', 'Myrtle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Sundsvall', 'Sweden', 'Delaware', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (118, 'Baturité', 'Brazil', 'Arizona', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Tangga', 'Indonesia', 'Main', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (174, 'Wonokerso', 'Indonesia', 'Stephen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (704, 'Salgar', 'Colombia', 'Atwood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (701, 'Pytalovo', 'Russia', 'Darwin', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (641, 'Huambo', 'Angola', 'Eagan', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (629, 'Dolní Kounice', 'Czech Republic', 'North', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (899, 'Xufu', 'China', 'Moose', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (906, 'San Quintin', 'Philippines', 'Twin Pines', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (542, 'Ciodeng', 'Indonesia', 'Hazelcrest', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (745, 'Toledo', 'United States', 'Sutteridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (643, 'Katabu', 'Indonesia', 'Jenifer', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (708, 'Muqui', 'Peru', 'Oxford', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (480, 'Leeuwarden', 'Netherlands', 'Coleman', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (606, 'Sanlicheng', 'China', 'Dahle', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (931, 'Bomadi', 'Nigeria', 'Anthes', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (183, 'Baltimore', 'United States', 'Vera', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Sexiong', 'China', 'Nelson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (978, 'Rey', 'Iran', 'Corben', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (361, 'Tournon-sur-Rhône', 'France', 'Donald', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (889, 'Chunhu', 'China', 'Lighthouse Bay', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (398, 'Hongkou', 'China', 'Vera', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (469, 'Meukek', 'Indonesia', 'Manitowish', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (682, 'Lisewo', 'Poland', 'Pennsylvania', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (504, 'Jega', 'Nigeria', 'Marcy', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (286, 'Kasreman', 'Indonesia', 'Carpenter', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (721, 'Qiaonan', 'China', 'Ridge Oak', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Saguing', 'Philippines', 'Katie', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (830, 'Saskatoon', 'Canada', 'Dryden', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (955, 'Sa‘sa‘', 'Syria', 'Swallow', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (964, 'Nichinan', 'Japan', 'Basil', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (904, 'Zawichost', 'Poland', 'School', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (747, 'Lakeland', 'United States', 'High Crossing', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (844, 'Colmar', 'France', 'Michigan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (880, 'Gwaram', 'Nigeria', 'Carioca', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (817, 'Chernelytsya', 'Ukraine', 'Monument', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (383, 'Aveiras de Cima', 'Portugal', 'Buena Vista', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (688, 'El Zapote', 'Mexico', 'Fairfield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (992, 'Kohtla-Järve', 'Estonia', 'Bunker Hill', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (87, 'Khairpur', 'Pakistan', 'Hallows', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (371, 'Bavorov', 'Czech Republic', 'Scott', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (863, 'Zongzhai', 'China', 'Truax', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (993, 'Phù Mỹ', 'Vietnam', 'Montana', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Xujiafang', 'China', 'Almo', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (3, 'Jelat', 'Indonesia', 'Declaration', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (424, 'Dieppe', 'France', 'Ridge Oak', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (334, 'Hondo Valle', 'Dominican Republic', 'Blue Bill Park', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (145, 'Koror Town', 'Palau', 'Morning', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (655, 'Lais', 'Philippines', 'Fair Oaks', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Zhubei', 'Taiwan', 'Loomis', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (642, 'Pittsburgh', 'United States', 'Commercial', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (559, 'Nizhniy Bestyakh', 'Russia', 'Scofield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (495, 'Yanyang', 'China', '6th', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Bijia', 'China', 'Vahlen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (971, 'El Parco District', 'Peru', 'Bartelt', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (547, 'Springbok', 'South Africa', 'Muir', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (681, 'Salgado', 'Brazil', 'Heath', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (732, 'Chwałowice', 'Poland', 'Mallard', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (348, 'Paratinga', 'Brazil', '1st', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (427, 'Da’an', 'China', 'Pleasure', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (92, 'Namling', 'China', 'Pierstorff', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (783, 'Gävle', 'Sweden', 'Summer Ridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (140, 'Psáry', 'Czech Republic', 'Erie', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (136, 'Brochów', 'Poland', 'Fairview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (510, 'San Francisco', 'Mexico', 'Aberg', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (785, 'Ulaandel', 'Mongolia', 'Hallows', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (753, 'Ash Shaḩānīyah', 'Qatar', 'Valley Edge', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Ponta Delgada', 'Portugal', 'Spenser', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (804, 'Tabalosos', 'Peru', 'Vernon', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (804, 'Geshan', 'China', 'Ohio', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (887, 'Smokvica', 'Croatia', 'Southridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (675, 'Ýdra', 'Greece', 'Pepper Wood', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (458, 'Presidente Prudente', 'Brazil', 'Pine View', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (392, 'Ponte da Pedra', 'Portugal', 'Main', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (803, 'Leles', 'Indonesia', 'Stang', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (674, 'Changkeng', 'China', 'Hintze', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (419, 'Ruda-Huta', 'Poland', 'Scott', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (590, 'Blois', 'France', 'Summer Ridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (263, 'Banjar Sebual', 'Indonesia', 'Mifflin', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (407, 'Quetigny', 'France', 'Elmside', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (221, 'Gaoping', 'China', 'North', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (588, 'Zhangbagou', 'China', 'Prentice', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (129, 'Ar Ru’ays', 'Qatar', 'Westridge', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (875, 'Karmah an Nuzul', 'Sudan', 'Vahlen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (366, 'Fucheng', 'China', 'Granby', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Plaški', 'Croatia', 'Meadow Vale', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (285, 'Villa Florida', 'Paraguay', 'Springview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (500, 'Krajan Sale', 'Indonesia', 'Mesta', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (973, 'Gammad', 'Philippines', 'David', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Kajatian', 'Philippines', 'Towne', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (447, 'Kiihtelysvaara', 'Finland', 'Sunbrook', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (744, 'Santo Niño', 'Philippines', 'Merrick', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (753, 'Bahāwalpur', 'Pakistan', 'Jenna', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (180, 'Cervantes', 'Philippines', 'Scofield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (670, 'Stockholm', 'Sweden', 'Sundown', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (885, 'Sunne', 'Sweden', 'Ryan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (93, 'Pedinó', 'Greece', 'Colorado', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (507, 'Melioratyvne', 'Ukraine', 'Heffernan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (63, 'Klenak', 'Serbia', 'Ramsey', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (194, 'Firovo', 'Russia', 'Eastwood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (493, 'Nandasmo', 'Nicaragua', 'Nelson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (792, 'Curiapo', 'Venezuela', 'Pleasure', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (679, 'Botshabelo', 'South Africa', 'Clemons', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (644, 'Baisha', 'China', 'High Crossing', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (954, 'Sabi', 'Gambia', 'Shopko', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (44, 'Viekšniai', 'Lithuania', 'Vermont', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (833, 'Heping', 'China', 'Pawling', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (356, 'Mosteiros', 'Portugal', 'Hansons', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (739, 'Grahamstown', 'South Africa', 'Autumn Leaf', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (995, 'Taiping', 'China', 'Dapin', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (76, 'Zhouxi', 'China', 'Tony', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (592, 'Sestroretsk', 'Russia', 'Westport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (37, 'Armenia', 'Colombia', 'Ramsey', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (766, 'Porteirinha', 'Brazil', 'Crowley', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (102, 'Paraíso', 'Portugal', 'Oxford', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (496, 'Rukunlima Bawah', 'Indonesia', 'Jay', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (788, 'Nancheng', 'China', 'Memorial', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (220, 'Barrhead', 'Canada', 'Kennedy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (363, 'Chishtiān Mandi', 'Pakistan', 'Vermont', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (749, 'Bussum', 'Netherlands', 'Oriole', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (262, 'Las Higueras', 'Argentina', 'Park Meadow', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (276, 'Gafsa', 'Tunisia', 'Pawling', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (325, 'Gupakan', 'Indonesia', 'Novick', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (621, 'Nancha', 'China', 'Upham', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (291, 'Calimita', 'Colombia', 'Muir', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (702, 'Resistencia', 'Argentina', 'School', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (222, 'Gornyy', 'Russia', 'Sycamore', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (517, 'Tapada das Mercês', 'Portugal', 'Annamark', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (659, 'Gornja Koprivna', 'Bosnia and Herzegovina', 'Independence', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (743, 'Taypano', 'Philippines', 'Chinook', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (513, 'Puhechang', 'China', 'Chive', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (161, 'Villanueva', 'Philippines', 'Gale', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (373, 'Dupnitsa', 'Bulgaria', 'Tennyson', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (945, 'Biała', 'Poland', 'Raven', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (534, 'Licheng', 'China', 'Aberg', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (690, 'Karatsu', 'Japan', 'Gateway', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (236, 'Saint-Amand-les-Eaux', 'France', 'Pond', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (755, 'Santa Maria do Souto', 'Portugal', 'Marcy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (344, 'Little Rock', 'United States', 'Del Mar', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (924, 'Fresnes', 'France', 'Manitowish', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (295, 'Luniao', 'China', 'Delladonna', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (10, 'Göteborg', 'Sweden', 'Sunnyside', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (831, 'Madalum', 'Philippines', 'Scofield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (82, 'Kandana', 'Sri Lanka', 'Arizona', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (468, 'Zhongshi', 'China', 'Sage', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (773, 'Karjalohja', 'Finland', 'Redwing', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (3, 'Mozdok', 'Russia', 'Manitowish', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (926, 'Chvaletice', 'Czech Republic', 'Carpenter', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Vřesina', 'Czech Republic', 'Twin Pines', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (646, 'Shiozawa', 'Japan', 'Huxley', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (685, 'Göteborg', 'Sweden', 'Granby', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (831, 'Raemude', 'Indonesia', 'Badeau', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (341, 'Nūrābād', 'Iran', 'Clyde Gallagher', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (690, 'Rislane', 'Morocco', 'Hoepker', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (985, 'Atsipópoulon', 'Greece', 'New Castle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (274, 'Loum', 'Cameroon', 'Kinsman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (677, 'Jingnao', 'China', 'Montana', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (613, 'Santa Fé do Sul', 'Brazil', 'Southridge', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (306, 'Odintsovo', 'Russia', 'Mallard', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (479, 'Atlanta', 'United States', 'Nancy', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (206, 'Semuda', 'Indonesia', 'Melrose', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (386, 'Zharkent', 'Kazakhstan', 'Quincy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (156, 'Gunung Talang', 'Indonesia', 'Londonderry', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Paso de Indios', 'Argentina', 'Kenwood', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (393, 'Rahama', 'Nigeria', 'Gina', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (197, 'Palmira', 'Cuba', 'Farragut', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Castañas', 'Philippines', 'Dakota', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (382, 'Caridade', 'Portugal', 'Rowland', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (541, 'Scholkine', 'Ukraine', 'Esker', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Demuk', 'Indonesia', 'Pankratz', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (729, 'Kurbnesh', 'Albania', 'Golf Course', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Perez', 'Philippines', 'Mosinee', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (49, 'Nianyushan', 'China', 'Meadow Ridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (321, 'Barra', 'Brazil', 'Stephen', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Issa', 'Russia', 'Waywood', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (206, 'Daxin', 'China', 'Straubel', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (543, 'Sukadana', 'Indonesia', 'Londonderry', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Atabayan', 'Philippines', 'Susan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (835, 'Marco', 'Brazil', 'Beilfuss', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (470, 'Bejucal', 'Cuba', 'Thackeray', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (7, 'Soanierana Ivongo', 'Madagascar', 'Butterfield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (346, 'Storozhevaya', 'Russia', 'South', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (716, 'Tiro', 'Indonesia', 'Corry', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (200, 'Novolugovoye', 'Russia', 'Sherman', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (641, 'Soa', 'Indonesia', 'Jenna', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (309, 'Narbonne', 'France', 'Cottonwood', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Nurota Shahri', 'Uzbekistan', 'Warbler', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (805, 'Niš', 'Serbia', 'Weeping Birch', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (524, 'Arras', 'France', 'Tennyson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (527, 'Kangping', 'China', 'Bashford', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Runting', 'Indonesia', 'Mendota', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (343, 'Przystajń', 'Poland', 'Sage', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (410, 'Pedro Leopoldo', 'Brazil', 'Lawn', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (699, 'Beaumont', 'Canada', 'Mandrake', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (922, 'Malishka', 'Armenia', 'David', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (145, 'Isyangulovo', 'Russia', 'Holy Cross', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (758, 'João Pessoa', 'Brazil', 'Fair Oaks', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (127, 'Yeysk', 'Russia', 'Reinke', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (210, 'Rrasa e Sipërme', 'Albania', 'Anthes', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (563, 'Gornje Živinice', 'Bosnia and Herzegovina', 'Ridgeway', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (770, 'Grenoble', 'France', 'Park Meadow', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (467, 'Ajaccio', 'France', 'Prairieview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (265, 'El Guapinol', 'Honduras', 'Upham', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (406, 'Sim', 'Russia', 'Ryan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (925, 'Abū Mūsā', 'Iran', 'Armistice', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (248, 'Guangning', 'China', 'Northview', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (345, 'Wang Saphung', 'Thailand', 'Waxwing', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (369, 'General Alvear', 'Argentina', 'Arrowood', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (907, 'Villavicencio', 'Colombia', 'Dorton', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (528, 'Camino Real', 'Mexico', 'Amoth', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (260, 'Karsin', 'Poland', 'La Follette', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Farīdpur', 'Bangladesh', 'Northland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'Thị Trấn Quảng Uyên', 'Vietnam', 'Hazelcrest', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (903, 'Zabaykal’sk', 'Russia', '1st', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (995, 'Paipa', 'Colombia', 'Elka', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (450, 'São Tomé', 'Portugal', 'Eliot', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (877, 'Hollola', 'Finland', 'Village', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (183, 'Xingzhen', 'China', 'Gina', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Krasnyy Yar', 'Russia', 'Stoughton', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (153, 'Kiukasen', 'Indonesia', 'Dahle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (420, 'Rochester', 'United States', 'Hagan', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (259, 'Melaka', 'Malaysia', 'Farwell', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (512, 'Tarasovskiy', 'Russia', 'Green', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (82, 'Aş Şūrah aş Şaghīrah', 'Syria', 'Nancy', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (192, 'Gibsons', 'Canada', 'Oxford', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (37, 'Sanlicheng', 'China', 'Fremont', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (589, 'Marly-le-Roi', 'France', 'Merry', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (352, 'Inđija', 'Serbia', 'Lyons', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (475, 'Mirecourt', 'France', 'Sunfield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (304, 'Peicheng', 'China', 'Warrior', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (984, 'Yuejin', 'China', 'Blackbird', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (478, 'Puksoozero', 'Russia', 'Pleasure', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (233, 'Gupakan', 'Indonesia', 'Bultman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (270, 'Siguiri', 'Guinea', 'Blaine', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (747, 'Panshan', 'China', 'David', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (961, 'Onsala', 'Sweden', 'Hansons', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Moorreesburg', 'South Africa', 'Mesta', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (691, 'Akron', 'United States', 'Grim', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Štore', 'Slovenia', 'Dennis', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (502, 'Neepawa', 'Canada', 'Scoville', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (759, 'Tomilino', 'Russia', 'Summerview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (538, 'Macachín', 'Argentina', 'Fallview', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (514, 'Glugu', 'Indonesia', 'Golf View', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (904, 'Prince Rupert', 'Canada', 'Ridge Oak', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (71, 'Ocuviri', 'Peru', 'Blackbird', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (459, 'Nanyue', 'China', 'Paget', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (982, 'Huangjin', 'China', 'Swallow', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'Yangsan', 'South Korea', 'Alpine', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (165, 'Yanahuaya', 'Peru', 'Transport', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (668, 'Athlone', 'Ireland', 'Erie', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (917, 'Hanlin', 'China', 'Clyde Gallagher', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (801, 'Duqu', 'China', 'La Follette', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (425, 'Villa Nueva', 'Honduras', 'Fairfield', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (252, 'Shiqiao', 'China', 'Barnett', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Budapest', 'Hungary', 'Nancy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (94, 'Asquipata', 'Peru', 'Corry', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (435, 'Oehaunu', 'Indonesia', 'Lyons', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (839, 'Tsotsin-Yurt', 'Russia', 'Holy Cross', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (543, 'Gómez', 'Panama', 'Porter', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (914, 'Imeni Babushkina', 'Russia', 'Ilene', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (108, 'Tankhoy', 'Russia', 'Meadow Ridge', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Dobre', 'Poland', 'Independence', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Baro Kunda', 'Gambia', 'Continental', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (168, 'Oświęcim', 'Poland', 'Florence', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (5, 'Krajanpagowan', 'Indonesia', 'Mosinee', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (654, 'Santa Rita Aplaya', 'Philippines', 'Dryden', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (784, 'Legok', 'Indonesia', 'Trailsway', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (767, 'Weizhou', 'China', 'Myrtle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (8, 'Vila do Maio', 'Cape Verde', 'Meadow Ridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (307, 'Duqu', 'China', 'Montana', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (795, 'Washington', 'United States', 'Vidon', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (962, 'Los Aquijes', 'Peru', 'Swallow', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'La Libertad', 'Honduras', 'International', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (731, 'Guaxupé', 'Brazil', 'Muir', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (527, 'Qingfenglin', 'China', 'Michigan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (989, 'Pisões', 'Portugal', 'Sage', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (416, 'Krasnodar', 'Russia', 'Myrtle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (697, 'Götene', 'Sweden', 'Troy', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (537, 'Quilmaná', 'Peru', 'Mesta', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (536, 'Monteros', 'Argentina', 'Carioca', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (850, 'Al Majāridah', 'Saudi Arabia', 'Village Green', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (156, 'Takefu', 'Japan', 'Eagan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (728, 'Mayang', 'China', 'Charing Cross', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (512, 'Kanchanaburi', 'Thailand', 'Lillian', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (375, 'Cartagena', 'Philippines', 'Fairfield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (188, 'Strogino', 'Russia', 'Butternut', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (152, 'Dijon', 'France', 'Emmet', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (716, 'Tatrang', 'China', 'Northfield', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (991, 'Karlstad', 'Sweden', 'Manufacturers', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (571, 'Ekazhevo', 'Russia', 'Steensland', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (255, 'Kaeng Khro', 'Thailand', 'Cambridge', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (157, 'Tasböget', 'Kazakhstan', 'Schmedeman', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Kemil', 'Indonesia', 'Emmet', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (520, 'Sobrosa', 'Portugal', 'Claremont', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Coyaima', 'Colombia', 'Ruskin', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Baltimore', 'United States', 'Meadow Vale', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (294, 'Dayton', 'United States', 'Marquette', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Maracanaú', 'Brazil', 'Brown', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (369, 'Lingbei', 'China', 'Fulton', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (761, 'Xaçmaz', 'Azerbaijan', 'Brickson Park', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (217, 'Argostólion', 'Greece', 'Dovetail', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (54, 'Baiqi', 'China', 'Graceland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (448, 'Huating', 'China', 'Goodland', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (193, 'Jaroměřice nad Rokytnou', 'Czech Republic', 'Carey', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (734, 'Bantuanon', 'Philippines', 'Duke', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (403, 'Paidha', 'Uganda', 'Calypso', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (439, 'Lundo', 'Indonesia', 'Cordelia', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Seupakat', 'Indonesia', 'Veith', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (444, 'Kuloy', 'Russia', 'Express', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (651, 'Haysyn', 'Ukraine', 'Grover', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (643, 'Nozdrzec', 'Poland', 'Green Ridge', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (245, 'Caringin', 'Indonesia', 'Doe Crossing', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (798, 'Pasarbaru', 'Indonesia', 'Linden', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (890, 'Davila', 'Philippines', 'Harper', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (339, 'Tqibuli', 'Georgia', 'Helena', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (408, 'Sumbergebang', 'Indonesia', 'Surrey', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (437, 'Jadi', 'Indonesia', 'Merrick', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (926, 'Mekon', 'Indonesia', 'Dwight', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Chaman', 'Pakistan', 'Declaration', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Baihe', 'China', 'Straubel', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (143, 'Jiangchuanlu', 'China', 'Bonner', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (839, 'Bongandanga', 'Democratic Republic of the Congo', 'New Castle', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (750, 'Noemuti', 'Indonesia', 'Sloan', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Koutsopódi', 'Greece', 'Memorial', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (371, 'Minneapolis', 'United States', 'Melody', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (459, 'Beiyang', 'China', 'Jackson', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (10, 'Dalong', 'China', 'Glacier Hill', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (573, 'Mozhong', 'China', 'Donald', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (213, 'Rybinsk', 'Russia', 'Hansons', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (706, 'Mayahi', 'Niger', 'Jenna', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (723, 'Sabana de Parra', 'Venezuela', 'Walton', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (9, 'Alcáçovas', 'Portugal', 'Packers', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (930, 'Murmuiža', 'Latvia', 'Victoria', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (888, 'Golema Rečica', 'Macedonia', 'Reinke', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (473, 'Tanahwulan', 'Indonesia', 'Hoepker', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (445, 'Sukahening', 'Indonesia', 'Anzinger', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (530, 'Jianyangping', 'China', 'Killdeer', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (994, 'Jeziora Wielkie', 'Poland', 'Stuart', 'license', 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (363, 'Wendengying', 'China', 'Amoth', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (72, 'Ajax', 'Canada', 'Carioca', 'license', 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (467, 'Angao', 'China', 'Merry', 'license', 'Customer');
