insert into MODEL (model, type) values ('Tracker', '7 Seater');
insert into MODEL (model, type) values ('Suburban 1500', 'Electric');
insert into MODEL (model, type) values ('Sedona', '4x4');
insert into MODEL (model, type) values ('Wrangler', 'Hybrid');
insert into MODEL (model, type) values ('Cavalier', 'Vans & Trucks');
insert into MODEL (model, type) values ('Chariot', 'Electric');
insert into MODEL (model, type) values ('Th!nk', '4x4');
insert into MODEL (model, type) values ('Tucson', '7 Seater');
insert into MODEL (model, type) values ('T100', 'Vans & Trucks');
insert into MODEL (model, type) values ('Ram 2500', '4x4');
insert into MODEL (model, type) values ('7 Series', 'Vans & Trucks');
insert into MODEL (model, type) values ('Nitro', 'Vans & Trucks');
insert into MODEL (model, type) values ('Somerset', '4x4');
insert into MODEL (model, type) values ('Trans Sport', 'SUV');
insert into MODEL (model, type) values ('Pajero', 'Performance');
insert into MODEL (model, type) values ('Avenger', 'Vans & Trucks');
insert into MODEL (model, type) values ('300M', 'SUV');
insert into MODEL (model, type) values ('Focus', 'Hybrid');
insert into MODEL (model, type) values ('Mustang', 'Performance');
insert into MODEL (model, type) values ('Sentra', 'Electric');
insert into MODEL (model, type) values ('Element', 'Hatchback');
insert into MODEL (model, type) values ('Explorer', 'Hybrid');
insert into MODEL (model, type) values ('Impreza', 'SUV');
insert into MODEL (model, type) values ('Corvette', 'Electric');
insert into MODEL (model, type) values ('S-Series', '4x4');
insert into MODEL (model, type) values ('Insight', 'Vans & Trucks');
insert into MODEL (model, type) values ('LS', 'Hybrid');
insert into MODEL (model, type) values ('F250', 'Hybrid');
insert into MODEL (model, type) values ('Esprit', 'Hybrid');
insert into MODEL (model, type) values ('Achieva', '4x4');
insert into MODEL (model, type) values ('Elantra', 'Hybrid');
insert into MODEL (model, type) values ('Corrado', 'Electric');
insert into MODEL (model, type) values ('SL-Class', '4x4');
insert into MODEL (model, type) values ('Shadow', 'Hatchback');
insert into MODEL (model, type) values ('E-Class', 'Performance');
insert into MODEL (model, type) values ('Spectra', 'Electric');
insert into MODEL (model, type) values ('Altima', 'Electric');
insert into MODEL (model, type) values ('Equinox', 'Hatchback');
insert into MODEL (model, type) values ('Grand Prix', '7 Seater');
insert into MODEL (model, type) values ('Murciélago', 'Hybrid');
insert into MODEL (model, type) values ('Regal', 'Vans & Trucks');
insert into MODEL (model, type) values ('Bonneville', 'Hybrid');
insert into MODEL (model, type) values ('Rodeo Sport', 'Hatchback');
insert into MODEL (model, type) values ('Patriot', '7 Seater');
insert into MODEL (model, type) values ('Ram Van 2500', 'Performance');
insert into MODEL (model, type) values ('SLK-Class', 'SUV');
insert into MODEL (model, type) values ('CTS', 'Vans & Trucks');
insert into MODEL (model, type) values ('SSR', 'Hybrid');
insert into MODEL (model, type) values ('Paseo', 'Hybrid');
insert into MODEL (model, type) values ('Grand Prix', '4x4');
insert into MODEL (model, type) values ('F-Series', 'Electric');
insert into MODEL (model, type) values ('Range Rover', 'Electric');
insert into MODEL (model, type) values ('Century', '7 Seater');
insert into MODEL (model, type) values ('Voyager', 'Vans & Trucks');
insert into MODEL (model, type) values ('C/V', '4x4');
insert into MODEL (model, type) values ('F250', 'SUV');
insert into MODEL (model, type) values ('Z8', '7 Seater');
insert into MODEL (model, type) values ('SRX', '4x4');
insert into MODEL (model, type) values ('Crown Victoria', '7 Seater');
insert into MODEL (model, type) values ('Town & Country', '7 Seater');
insert into MODEL (model, type) values ('Impreza', '4x4');
insert into MODEL (model, type) values ('H2 SUV', 'Hybrid');
insert into MODEL (model, type) values ('Jetta', '7 Seater');
insert into MODEL (model, type) values ('Relay', '7 Seater');
insert into MODEL (model, type) values ('Bonneville', 'Hybrid');
insert into MODEL (model, type) values ('Maxima', 'SUV');
insert into MODEL (model, type) values ('Ciera', 'SUV');
insert into MODEL (model, type) values ('CC', '4x4');
insert into MODEL (model, type) values ('Fleetwood', 'Electric');
insert into MODEL (model, type) values ('Elantra', 'Vans & Trucks');
insert into MODEL (model, type) values ('Mirage', 'SUV');
insert into MODEL (model, type) values ('350Z', 'Vans & Trucks');
insert into MODEL (model, type) values ('Sierra 3500', 'Hybrid');
insert into MODEL (model, type) values ('Sentra', 'Performance');
insert into MODEL (model, type) values ('D150', 'Hatchback');
insert into MODEL (model, type) values ('Trans Sport', 'Electric');
insert into MODEL (model, type) values ('Viper', 'Performance');
insert into MODEL (model, type) values ('Edge', '7 Seater');
insert into MODEL (model, type) values ('Tiburon', 'Hybrid');
insert into MODEL (model, type) values ('Solstice', 'Hybrid');
insert into MODEL (model, type) values ('Suburban 2500', 'Hybrid');
insert into MODEL (model, type) values ('Magnum', '4x4');
insert into MODEL (model, type) values ('968', 'Vans & Trucks');
insert into MODEL (model, type) values ('Justy', 'Hybrid');
insert into MODEL (model, type) values ('DTS', 'Electric');
insert into MODEL (model, type) values ('Rio', 'Electric');
insert into MODEL (model, type) values ('Sienna', '7 Seater');
insert into MODEL (model, type) values ('Escalade', 'Hybrid');
insert into MODEL (model, type) values ('Vibe', '7 Seater');
insert into MODEL (model, type) values ('Quattroporte', 'Hatchback');
insert into MODEL (model, type) values ('DTS', 'Performance');
insert into MODEL (model, type) values ('Econoline E150', 'Hybrid');
insert into MODEL (model, type) values ('Bronco II', 'Performance');
insert into MODEL (model, type) values ('Camaro', 'Vans & Trucks');
insert into MODEL (model, type) values ('Passat', 'Electric');
insert into MODEL (model, type) values ('Range Rover', '7 Seater');
insert into MODEL (model, type) values ('Fury', 'Hatchback');
insert into MODEL (model, type) values ('Brooklands', 'Electric');
insert into MODEL (model, type) values ('Montero', '4x4');
insert into MODEL (model, type) values ('Range Rover Classic', 'Performance');
insert into MODEL (model, type) values ('Continental Super', '7 Seater');
insert into MODEL (model, type) values ('Tiguan', '4x4');
insert into MODEL (model, type) values ('Skylark', '7 Seater');
insert into MODEL (model, type) values ('RX', 'SUV');
insert into MODEL (model, type) values ('Corvette', 'Vans & Trucks');
insert into MODEL (model, type) values ('5 Series', 'Hybrid');
insert into MODEL (model, type) values ('Skylark', 'Hatchback');
insert into MODEL (model, type) values ('Trans Sport', 'SUV');
insert into MODEL (model, type) values ('RX-7', 'Electric');
insert into MODEL (model, type) values ('5 Series', 'Hybrid');
insert into MODEL (model, type) values ('Optima', '4x4');
insert into MODEL (model, type) values ('911', 'Performance');
insert into MODEL (model, type) values ('3500', 'SUV');
insert into MODEL (model, type) values ('Century', '7 Seater');
insert into MODEL (model, type) values ('Accord Crosstour', '4x4');
insert into MODEL (model, type) values ('GTI', '7 Seater');
insert into MODEL (model, type) values ('Previa', 'Performance');
insert into MODEL (model, type) values ('Mustang', 'SUV');
insert into MODEL (model, type) values ('F-Series Super Duty', 'Electric');
insert into MODEL (model, type) values ('X6', '7 Seater');
insert into MODEL (model, type) values ('Jetta', 'Vans & Trucks');
insert into MODEL (model, type) values ('Thunderbird', '4x4');
insert into MODEL (model, type) values ('Jetta', 'Vans & Trucks');
insert into MODEL (model, type) values ('C-Class', 'Hatchback');
insert into MODEL (model, type) values ('DB9', 'Hatchback');
insert into MODEL (model, type) values ('Thunderbird', '4x4');
insert into MODEL (model, type) values ('SJ', 'Hatchback');
insert into MODEL (model, type) values ('Regal', 'Hatchback');
insert into MODEL (model, type) values ('Grand Cherokee', 'Performance');
insert into MODEL (model, type) values ('Elan', 'Hybrid');
insert into MODEL (model, type) values ('Previa', '4x4');
insert into MODEL (model, type) values ('Cougar', 'Hatchback');
insert into MODEL (model, type) values ('Navigator L', 'Hatchback');
insert into MODEL (model, type) values ('Xterra', 'Hybrid');
insert into MODEL (model, type) values ('Continental Flying Spur', 'Electric');
insert into MODEL (model, type) values ('Suburban 2500', 'Electric');
insert into MODEL (model, type) values ('Camry', 'Hybrid');
insert into MODEL (model, type) values ('RS 6', 'Hybrid');
insert into MODEL (model, type) values ('Voyager', 'Vans & Trucks');
insert into MODEL (model, type) values ('RX-7', 'Hatchback');
insert into MODEL (model, type) values ('9000', 'Performance');
insert into MODEL (model, type) values ('Land Cruiser', '4x4');
insert into MODEL (model, type) values ('911', 'SUV');
insert into MODEL (model, type) values ('Mustang', 'Hybrid');
insert into MODEL (model, type) values ('Suburban 2500', 'Hybrid');
insert into MODEL (model, type) values ('Taurus', 'Performance');
insert into MODEL (model, type) values ('Q5', '4x4');
insert into MODEL (model, type) values ('Eclipse', '7 Seater');
insert into MODEL (model, type) values ('Silhouette', 'Hatchback');
insert into MODEL (model, type) values ('XJ Series', '7 Seater');
insert into MODEL (model, type) values ('X-90', 'Vans & Trucks');
insert into MODEL (model, type) values ('TL', 'SUV');
insert into MODEL (model, type) values ('RX', 'Electric');
insert into MODEL (model, type) values ('4Runner', '7 Seater');
insert into MODEL (model, type) values ('Highlander', '4x4');
insert into MODEL (model, type) values ('X6 M', 'Hybrid');
insert into MODEL (model, type) values ('GTI', 'Hatchback');
insert into MODEL (model, type) values ('Cutlass', 'Electric');
insert into MODEL (model, type) values ('TL', 'Electric');
insert into MODEL (model, type) values ('Ram 3500', 'Performance');
insert into MODEL (model, type) values ('Seville', 'SUV');
insert into MODEL (model, type) values ('Th!nk', '4x4');
insert into MODEL (model, type) values ('Santa Fe', 'Hatchback');
insert into MODEL (model, type) values ('Tredia', 'Hybrid');
insert into MODEL (model, type) values ('Sorento', 'SUV');
insert into MODEL (model, type) values ('Suburban 1500', 'Hatchback');
insert into MODEL (model, type) values ('Dakota', 'Electric');
insert into MODEL (model, type) values ('LeMans', '4x4');
insert into MODEL (model, type) values ('Arnage', 'Hatchback');
insert into MODEL (model, type) values ('Prelude', 'Hatchback');
insert into MODEL (model, type) values ('Cougar', 'Electric');
insert into MODEL (model, type) values ('Dakota Club', 'Vans & Trucks');
insert into MODEL (model, type) values ('Mountaineer', 'Hatchback');
insert into MODEL (model, type) values ('Defender', 'Electric');
insert into MODEL (model, type) values ('Endeavor', '4x4');
insert into MODEL (model, type) values ('GT500', 'Performance');
insert into MODEL (model, type) values ('2500', 'SUV');
insert into MODEL (model, type) values ('Neon', 'Hatchback');
insert into MODEL (model, type) values ('Avalon', 'SUV');
insert into MODEL (model, type) values ('760', 'Hybrid');
insert into MODEL (model, type) values ('Colt', '7 Seater');
insert into MODEL (model, type) values ('S-Class', 'SUV');
insert into MODEL (model, type) values ('Montana', 'SUV');
insert into MODEL (model, type) values ('Z4', 'Vans & Trucks');
insert into MODEL (model, type) values ('IS F', 'Electric');
insert into MODEL (model, type) values ('XLR', 'Hybrid');
insert into MODEL (model, type) values ('Miata MX-5', 'Hatchback');
insert into MODEL (model, type) values ('SL-Class', 'Vans & Trucks');
insert into MODEL (model, type) values ('Bronco', 'Performance');
insert into MODEL (model, type) values ('Town & Country', 'Hybrid');
insert into MODEL (model, type) values ('Navigator L', '7 Seater');
insert into MODEL (model, type) values ('Ranger', 'Hybrid');
insert into MODEL (model, type) values ('Murano', 'Vans & Trucks');
insert into MODEL (model, type) values ('Passat', 'Performance');
insert into MODEL (model, type) values ('Yukon XL 2500', '7 Seater');
insert into MODEL (model, type) values ('Sierra 1500', '4x4');
insert into MODEL (model, type) values ('SSR', 'SUV');
insert into MODEL (model, type) values ('Ram 2500', 'Electric');
insert into MODEL (model, type) values ('SL-Class', 'Vans & Trucks');
insert into MODEL (model, type) values ('Windstar', 'Electric');
insert into MODEL (model, type) values ('XC60', '7 Seater');
insert into MODEL (model, type) values ('88', 'Vans & Trucks');
insert into MODEL (model, type) values ('Diablo', 'Hybrid');
insert into MODEL (model, type) values ('Element', 'Electric');
insert into MODEL (model, type) values ('2500', 'Hatchback');
insert into MODEL (model, type) values ('S-Series', 'Performance');
insert into MODEL (model, type) values ('Ram 1500 Club', 'SUV');
insert into MODEL (model, type) values ('Silverado 1500', 'Vans & Trucks');
insert into MODEL (model, type) values ('Silverado 3500', '4x4');
insert into MODEL (model, type) values ('Legacy', 'Vans & Trucks');
insert into MODEL (model, type) values ('Focus', 'Performance');
insert into MODEL (model, type) values ('D250', 'Performance');
insert into MODEL (model, type) values ('Forester', 'Performance');
insert into MODEL (model, type) values ('Protege', 'Performance');
insert into MODEL (model, type) values ('Highlander', 'Vans & Trucks');
insert into MODEL (model, type) values ('Silverado 3500', '4x4');
insert into MODEL (model, type) values ('Rodeo', 'Electric');
insert into MODEL (model, type) values ('Discovery', '7 Seater');
insert into MODEL (model, type) values ('Space', 'Hatchback');
insert into MODEL (model, type) values ('Rio', 'Electric');
insert into MODEL (model, type) values ('Ranger', 'Hatchback');
insert into MODEL (model, type) values ('A8', 'SUV');
insert into MODEL (model, type) values ('MX-3', 'Electric');
insert into MODEL (model, type) values ('MDX', '7 Seater');
insert into MODEL (model, type) values ('612 Scaglietti', '4x4');
insert into MODEL (model, type) values ('E-Series', 'Electric');
insert into MODEL (model, type) values ('Stealth', 'Electric');
insert into MODEL (model, type) values ('Coachbuilder', '4x4');
insert into MODEL (model, type) values ('Armada', 'Hatchback');
insert into MODEL (model, type) values ('Crossfire Roadster', 'SUV');
insert into MODEL (model, type) values ('Corvette', '4x4');
insert into MODEL (model, type) values ('Stealth', 'Hatchback');
insert into MODEL (model, type) values ('A7', '4x4');
insert into MODEL (model, type) values ('Tahoe', 'Vans & Trucks');
insert into MODEL (model, type) values ('Mazda2', 'Hatchback');
insert into MODEL (model, type) values ('DB9 Volante', 'Electric');
insert into MODEL (model, type) values ('D350 Club', '4x4');
insert into MODEL (model, type) values ('Mirage', 'Electric');
insert into MODEL (model, type) values ('Solara', 'Electric');
insert into MODEL (model, type) values ('CX-7', 'Electric');
insert into MODEL (model, type) values ('MKS', 'Performance');
insert into MODEL (model, type) values ('S-Class', 'Hybrid');
insert into MODEL (model, type) values ('300ZX', 'Hatchback');
insert into MODEL (model, type) values ('Riviera', 'Electric');
insert into MODEL (model, type) values ('SL-Class', '4x4');
insert into MODEL (model, type) values ('Endeavor', 'Performance');
insert into MODEL (model, type) values ('Boxster', 'Vans & Trucks');
insert into MODEL (model, type) values ('Sierra 2500', '7 Seater');
insert into MODEL (model, type) values ('Z4', 'Hybrid');
insert into MODEL (model, type) values ('Brat', 'Vans & Trucks');
insert into MODEL (model, type) values ('SL-Class', 'Hatchback');
insert into MODEL (model, type) values ('Crown Victoria', '4x4');
insert into MODEL (model, type) values ('Outlander', 'Performance');
insert into MODEL (model, type) values ('Riviera', 'Hatchback');
insert into MODEL (model, type) values ('Sportage', 'SUV');
insert into MODEL (model, type) values ('E150', 'Hatchback');
insert into MODEL (model, type) values ('Odyssey', 'Electric');
insert into MODEL (model, type) values ('Savana 1500', 'Hatchback');
insert into MODEL (model, type) values ('80', 'Electric');
insert into MODEL (model, type) values ('Sequoia', 'Hybrid');
insert into MODEL (model, type) values ('960', 'Hatchback');
insert into MODEL (model, type) values ('Celica', '7 Seater');
insert into MODEL (model, type) values ('Mazda6', 'Electric');
insert into MODEL (model, type) values ('Murano', 'SUV');
insert into MODEL (model, type) values ('300CE', 'Hybrid');
insert into MODEL (model, type) values ('Panamera', 'Vans & Trucks');
insert into MODEL (model, type) values ('Panamera', 'Performance');
insert into MODEL (model, type) values ('Catera', '4x4');
insert into MODEL (model, type) values ('Cavalier', 'Electric');
insert into MODEL (model, type) values ('RL', 'Electric');
insert into MODEL (model, type) values ('3 Series', 'Hybrid');
insert into MODEL (model, type) values ('Sierra 3500', '7 Seater');
insert into MODEL (model, type) values ('X6 M', '7 Seater');
insert into MODEL (model, type) values ('Altima', 'Performance');
insert into MODEL (model, type) values ('Grand Prix', 'Hybrid');
insert into MODEL (model, type) values ('Mustang', 'Electric');
insert into MODEL (model, type) values ('Intrepid', 'Vans & Trucks');
insert into MODEL (model, type) values ('GL-Class', '4x4');
insert into MODEL (model, type) values ('Mountaineer', 'Hatchback');
insert into MODEL (model, type) values ('Express 2500', '7 Seater');
insert into MODEL (model, type) values ('B2600', 'Hatchback');
insert into MODEL (model, type) values ('Trans Sport', '4x4');
insert into MODEL (model, type) values ('XJ Series', 'Hybrid');
insert into MODEL (model, type) values ('M3', 'Hybrid');
insert into MODEL (model, type) values ('Swift', 'Vans & Trucks');
insert into MODEL (model, type) values ('Metro', '4x4');
insert into MODEL (model, type) values ('Savana 2500', '7 Seater');
insert into MODEL (model, type) values ('Mariner', 'Performance');
insert into MODEL (model, type) values ('Freelander', 'Electric');
insert into MODEL (model, type) values ('Baja', 'Vans & Trucks');
insert into MODEL (model, type) values ('Cavalier', 'Hatchback');
insert into MODEL (model, type) values ('Camaro', 'Performance');
insert into MODEL (model, type) values ('MKT', 'Hatchback');
insert into MODEL (model, type) values ('GTO', 'Hatchback');
insert into MODEL (model, type) values ('G6', '4x4');
insert into MODEL (model, type) values ('Golf', 'Vans & Trucks');
insert into MODEL (model, type) values ('Sequoia', '4x4');
insert into MODEL (model, type) values ('612 Scaglietti', 'SUV');
insert into MODEL (model, type) values ('90', '7 Seater');
insert into MODEL (model, type) values ('Challenger', 'Electric');
insert into MODEL (model, type) values ('Horizon', '7 Seater');
insert into MODEL (model, type) values ('XC70', '4x4');
insert into MODEL (model, type) values ('Ridgeline', 'Electric');
insert into MODEL (model, type) values ('Suburban 2500', 'SUV');
insert into MODEL (model, type) values ('Avalon', '7 Seater');
insert into MODEL (model, type) values ('Veracruz', 'Hybrid');
insert into MODEL (model, type) values ('QX', 'Hybrid');
insert into MODEL (model, type) values ('Grand Marquis', 'Performance');
insert into MODEL (model, type) values ('Carens', 'SUV');
insert into MODEL (model, type) values ('Range Rover', 'Performance');
insert into MODEL (model, type) values ('458 Italia', 'Vans & Trucks');
insert into MODEL (model, type) values ('Lumina', 'Hatchback');
insert into MODEL (model, type) values ('Capri', 'Hatchback');
insert into MODEL (model, type) values ('Phantom', '7 Seater');
insert into MODEL (model, type) values ('S80', 'Hatchback');
insert into MODEL (model, type) values ('Escalade EXT', 'Hybrid');
insert into MODEL (model, type) values ('Monterey', '4x4');
insert into MODEL (model, type) values ('Fusion', '4x4');
insert into MODEL (model, type) values ('E-Class', 'Hatchback');
insert into MODEL (model, type) values ('LX', 'Electric');
insert into MODEL (model, type) values ('GL-Class', 'Performance');
insert into MODEL (model, type) values ('Accent', 'Hybrid');
insert into MODEL (model, type) values ('ES', 'Hybrid');
insert into MODEL (model, type) values ('Taurus', 'Hatchback');
insert into MODEL (model, type) values ('Escalade ESV', 'Vans & Trucks');
insert into MODEL (model, type) values ('Freestar', 'Performance');
insert into MODEL (model, type) values ('Touareg', 'Vans & Trucks');
insert into MODEL (model, type) values ('Sunfire', '7 Seater');
insert into MODEL (model, type) values ('FX', 'SUV');
insert into MODEL (model, type) values ('TSX', '4x4');
insert into MODEL (model, type) values ('Beretta', 'Hatchback');
insert into MODEL (model, type) values ('Grand Marquis', 'Hybrid');
insert into MODEL (model, type) values ('Optima', 'Electric');
insert into MODEL (model, type) values ('Matrix', '7 Seater');
insert into MODEL (model, type) values ('Yukon XL 1500', '4x4');
insert into MODEL (model, type) values ('VS Commodore', 'Performance');
insert into MODEL (model, type) values ('E350', 'Hybrid');
insert into MODEL (model, type) values ('Grand Marquis', '4x4');
insert into MODEL (model, type) values ('B-Series Plus', 'Hybrid');
insert into MODEL (model, type) values ('Neon', 'Vans & Trucks');
insert into MODEL (model, type) values ('Grand Prix', 'Hatchback');
insert into MODEL (model, type) values ('Golf III', '4x4');
insert into MODEL (model, type) values ('Avalanche', 'Electric');
insert into MODEL (model, type) values ('Camry', '4x4');
insert into MODEL (model, type) values ('F250', 'SUV');
insert into MODEL (model, type) values ('GranSport', 'Hatchback');
insert into MODEL (model, type) values ('Windstar', 'SUV');
insert into MODEL (model, type) values ('Safari', 'Vans & Trucks');
insert into MODEL (model, type) values ('Navigator', 'Vans & Trucks');
insert into MODEL (model, type) values ('Riviera', 'Vans & Trucks');
insert into MODEL (model, type) values ('57', 'Performance');
insert into MODEL (model, type) values ('Skylark', 'Hybrid');
insert into MODEL (model, type) values ('F-Series', '7 Seater');
insert into MODEL (model, type) values ('RAV4', '4x4');
insert into MODEL (model, type) values ('80', 'Vans & Trucks');
insert into MODEL (model, type) values ('Cabriolet', 'Performance');
insert into MODEL (model, type) values ('MR2', 'Hatchback');
insert into MODEL (model, type) values ('Accent', 'Electric');
insert into MODEL (model, type) values ('5000CS', 'Hybrid');
insert into MODEL (model, type) values ('Express 2500', 'Hybrid');
insert into MODEL (model, type) values ('Grand Prix', 'Hatchback');
insert into MODEL (model, type) values ('Verano', 'Performance');
insert into MODEL (model, type) values ('Safari', 'Vans & Trucks');
insert into MODEL (model, type) values ('Amanti', 'Hatchback');
insert into MODEL (model, type) values ('Pathfinder', 'Hatchback');
insert into MODEL (model, type) values ('Altima', 'SUV');
insert into MODEL (model, type) values ('Escalade EXT', 'SUV');
insert into MODEL (model, type) values ('Envoy XL', '4x4');
insert into MODEL (model, type) values ('Grand Caravan', 'SUV');
insert into MODEL (model, type) values ('Regal', 'Performance');
insert into MODEL (model, type) values ('F250', '4x4');
insert into MODEL (model, type) values ('S-Class', 'Electric');
insert into MODEL (model, type) values ('E250', 'Hybrid');
insert into MODEL (model, type) values ('Grand Prix', 'Hybrid');
insert into MODEL (model, type) values ('Sable', '7 Seater');
insert into MODEL (model, type) values ('Golf', 'Performance');
insert into MODEL (model, type) values ('M6', 'Vans & Trucks');
insert into MODEL (model, type) values ('Suburban 1500', 'Vans & Trucks');
insert into MODEL (model, type) values ('Continental', 'Electric');
insert into MODEL (model, type) values ('5000S', 'Electric');
insert into MODEL (model, type) values ('Grand Cherokee', 'SUV');
insert into MODEL (model, type) values ('F150', '4x4');
insert into MODEL (model, type) values ('Corolla', 'SUV');
insert into MODEL (model, type) values ('Riviera', 'Electric');
insert into MODEL (model, type) values ('Cavalier', 'Hatchback');
insert into MODEL (model, type) values ('S2000', 'SUV');
insert into MODEL (model, type) values ('S6', 'Vans & Trucks');
insert into MODEL (model, type) values ('7 Series', 'Hybrid');
insert into MODEL (model, type) values ('Quattro', '7 Seater');
insert into MODEL (model, type) values ('LeSabre', 'Hatchback');
insert into MODEL (model, type) values ('CR-X', 'Performance');
insert into MODEL (model, type) values ('LeSabre', '4x4');
insert into MODEL (model, type) values ('Cabriolet', '4x4');
insert into MODEL (model, type) values ('Continental Super', 'Hatchback');
insert into MODEL (model, type) values ('PT Cruiser', 'Electric');
insert into MODEL (model, type) values ('1500', 'SUV');
insert into MODEL (model, type) values ('Galant', '7 Seater');
insert into MODEL (model, type) values ('Aerostar', '4x4');
insert into MODEL (model, type) values ('Challenger', 'Electric');
insert into MODEL (model, type) values ('Tacoma Xtra', 'Hybrid');
insert into MODEL (model, type) values ('928', 'Electric');
insert into MODEL (model, type) values ('S-Type', 'Electric');
insert into MODEL (model, type) values ('Range Rover', '7 Seater');
insert into MODEL (model, type) values ('Neon', 'Vans & Trucks');
insert into MODEL (model, type) values ('Mark VIII', '7 Seater');
insert into MODEL (model, type) values ('E-Class', '7 Seater');
insert into MODEL (model, type) values ('i-280', '4x4');
insert into MODEL (model, type) values ('Sierra 3500', 'Vans & Trucks');
insert into MODEL (model, type) values ('Savana 1500', 'Performance');
insert into MODEL (model, type) values ('C/V', 'Hatchback');
insert into MODEL (model, type) values ('Taurus', 'Hatchback');
insert into MODEL (model, type) values ('Leone', 'Vans & Trucks');
insert into MODEL (model, type) values ('RAV4', 'Hybrid');
insert into MODEL (model, type) values ('Jetta III', '4x4');
insert into MODEL (model, type) values ('9000', 'Hybrid');
insert into MODEL (model, type) values ('9-3', 'Performance');
insert into MODEL (model, type) values ('3500', 'Performance');
insert into MODEL (model, type) values ('Q', 'Hatchback');
insert into MODEL (model, type) values ('FCX Clarity', 'Electric');
insert into MODEL (model, type) values ('929', 'SUV');
insert into MODEL (model, type) values ('500SEL', 'Electric');
insert into MODEL (model, type) values ('Freestar', 'Hatchback');
insert into MODEL (model, type) values ('New Beetle', 'Vans & Trucks');
insert into MODEL (model, type) values ('Aerostar', '7 Seater');
insert into MODEL (model, type) values ('Civic', '7 Seater');
insert into MODEL (model, type) values ('Passport', 'Vans & Trucks');
insert into MODEL (model, type) values ('S-Class', 'Vans & Trucks');
insert into MODEL (model, type) values ('Camry Hybrid', 'Hatchback');
insert into MODEL (model, type) values ('Town & Country', '7 Seater');
insert into MODEL (model, type) values ('A4', '4x4');
insert into MODEL (model, type) values ('MDX', '7 Seater');
insert into MODEL (model, type) values ('C70', 'Electric');
insert into MODEL (model, type) values ('Sonoma', 'Hybrid');
insert into MODEL (model, type) values ('Vigor', 'Hybrid');
insert into MODEL (model, type) values ('Century', 'Hybrid');
insert into MODEL (model, type) values ('M3', 'Hybrid');
insert into MODEL (model, type) values ('CLS-Class', '7 Seater');
insert into MODEL (model, type) values ('Integra', 'Performance');
insert into MODEL (model, type) values ('Sonoma Club Coupe', '7 Seater');
insert into MODEL (model, type) values ('G', 'SUV');
insert into MODEL (model, type) values ('FX', 'SUV');
insert into MODEL (model, type) values ('C8', 'Performance');
insert into MODEL (model, type) values ('Colorado', 'Performance');
insert into MODEL (model, type) values ('G', 'Electric');
insert into MODEL (model, type) values ('Camry', 'Hybrid');
insert into MODEL (model, type) values ('E350', '4x4');
insert into MODEL (model, type) values ('Cooper Clubman', '7 Seater');
insert into MODEL (model, type) values ('CX-7', 'Performance');
insert into MODEL (model, type) values ('Jetta', 'Vans & Trucks');
insert into MODEL (model, type) values ('Esteem', 'Electric');
insert into MODEL (model, type) values ('Navajo', '7 Seater');
insert into MODEL (model, type) values ('Protege', '7 Seater');
insert into MODEL (model, type) values ('Baja', 'Hybrid');
insert into MODEL (model, type) values ('xD', 'Vans & Trucks');
insert into MODEL (model, type) values ('Grand Voyager', 'Hybrid');
insert into MODEL (model, type) values ('Contour', '7 Seater');
insert into MODEL (model, type) values ('2500', '4x4');
insert into MODEL (model, type) values ('Prius Plug-in', 'Electric');
insert into MODEL (model, type) values ('Firefly', '7 Seater');
insert into MODEL (model, type) values ('626', '7 Seater');
insert into MODEL (model, type) values ('88', 'Hatchback');
insert into MODEL (model, type) values ('Truck', 'Hatchback');
insert into MODEL (model, type) values ('C70', 'Hybrid');
insert into MODEL (model, type) values ('Fusion', 'Performance');
insert into MODEL (model, type) values ('Concorde', 'Electric');
insert into MODEL (model, type) values ('B2600', 'Electric');
insert into MODEL (model, type) values ('Challenger', 'Performance');
insert into MODEL (model, type) values ('Breeze', 'Hatchback');
insert into MODEL (model, type) values ('Silhouette', 'SUV');
insert into MODEL (model, type) values ('Riviera', '4x4');
insert into MODEL (model, type) values ('G-Series G30', 'SUV');
insert into MODEL (model, type) values ('Savana 1500', 'Vans & Trucks');
insert into MODEL (model, type) values ('Grand Caravan', 'SUV');
insert into MODEL (model, type) values ('Grand Marquis', '4x4');
insert into MODEL (model, type) values ('F450', 'Vans & Trucks');
insert into MODEL (model, type) values ('Ram', '7 Seater');
insert into MODEL (model, type) values ('Expedition', 'SUV');
insert into MODEL (model, type) values ('A4', 'Vans & Trucks');
insert into MODEL (model, type) values ('Armada', '7 Seater');
insert into MODEL (model, type) values ('Vandura 1500', 'Hatchback');
insert into MODEL (model, type) values ('Corvette', 'SUV');
insert into MODEL (model, type) values ('Z8', 'Electric');
insert into MODEL (model, type) values ('Caliber', 'Vans & Trucks');
insert into MODEL (model, type) values ('Ram 1500 Club', 'SUV');
insert into MODEL (model, type) values ('Focus', 'SUV');
insert into MODEL (model, type) values ('9-3', 'SUV');
insert into MODEL (model, type) values ('Cherokee', '7 Seater');
insert into MODEL (model, type) values ('Frontier', '7 Seater');
insert into MODEL (model, type) values ('Golf', 'Hybrid');
insert into MODEL (model, type) values ('Venture', 'SUV');
insert into MODEL (model, type) values ('Pacifica', 'SUV');
insert into MODEL (model, type) values ('K5 Blazer', 'SUV');
insert into MODEL (model, type) values ('Aerio', '4x4');
insert into MODEL (model, type) values ('Envoy XL', 'Performance');
insert into MODEL (model, type) values ('Lumina', '7 Seater');
insert into MODEL (model, type) values ('XC70', '4x4');
insert into MODEL (model, type) values ('Trooper', 'Vans & Trucks');
insert into MODEL (model, type) values ('RX-7', 'Electric');
insert into MODEL (model, type) values ('CLK-Class', 'Vans & Trucks');
insert into MODEL (model, type) values ('E-Series', 'SUV');
