insert into MODEL (model, type, manufacturer) values ('XT', 'Performance', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('Pathfinder', '7 Seater', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('DeVille', 'Vans & Trucks', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Raider', 'SUV', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Prizm', '4x4', 'Geo');
insert into MODEL (model, type, manufacturer) values ('3500 Club Coupe', 'Hatchback', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Yukon Denali', 'Electric', 'GMC');
insert into MODEL (model, type, manufacturer) values ('F350', 'Hatchback', 'Ford');
insert into MODEL (model, type, manufacturer) values ('A6', 'Hatchback', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Vandura 1500', '7 Seater', 'GMC');
insert into MODEL (model, type, manufacturer) values ('SLR McLaren', '7 Seater', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('207', 'Electric', 'Peugeot');
insert into MODEL (model, type, manufacturer) values ('Grand Caravan', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('MKZ', '7 Seater', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('Explorer', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Avalanche', '7 Seater', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Trans Sport', 'SUV', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('CR-V', 'Electric', 'Honda');
insert into MODEL (model, type, manufacturer) values ('Savana 1500', 'Electric', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Club Wagon', 'Hybrid', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Century', 'Performance', 'Buick');
insert into MODEL (model, type, manufacturer) values ('Cutlass Supreme', 'Hybrid', 'Oldsmobile');
insert into MODEL (model, type, manufacturer) values ('Jimmy', 'Performance', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Sentra', 'Hybrid', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Escort', 'SUV', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Taurus', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Swift', 'Performance', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Neon', 'SUV', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Avalanche 2500', '4x4', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Skylark', 'SUV', 'Buick');
insert into MODEL (model, type, manufacturer) values ('Thunderbird', 'Hybrid', 'Ford');
insert into MODEL (model, type, manufacturer) values ('X-90', 'Performance', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Accent', '4x4', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Spectra', 'Performance', 'Kia');
insert into MODEL (model, type, manufacturer) values ('Quest', '7 Seater', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Civic', 'Performance', 'Honda');
insert into MODEL (model, type, manufacturer) values ('del Sol', '7 Seater', 'Honda');
insert into MODEL (model, type, manufacturer) values ('SLK-Class', 'Hatchback', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Suburban 1500', 'Hybrid', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Silverado 2500', 'Hatchback', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('H1', '4x4', 'Hummer');
insert into MODEL (model, type, manufacturer) values ('GTO', 'Electric', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('LeMans', 'Hatchback', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('LS', 'Performance', 'Lexus');
insert into MODEL (model, type, manufacturer) values ('Fox', '7 Seater', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('Titan', 'SUV', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('57', 'Performance', 'Maybach');
insert into MODEL (model, type, manufacturer) values ('Caprice', 'SUV', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('2500', 'SUV', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Tundra', 'Electric', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('B-Series', 'Performance', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('E-Series', 'Electric', 'Ford');
insert into MODEL (model, type, manufacturer) values ('A3', '4x4', 'Audi');
insert into MODEL (model, type, manufacturer) values ('612 Scaglietti', 'Performance', 'Ferrari');
insert into MODEL (model, type, manufacturer) values ('Precis', '7 Seater', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Millenia', 'Electric', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('430', 'Electric', 'Maserati');
insert into MODEL (model, type, manufacturer) values ('Tucson', 'Hatchback', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Continental', '4x4', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('CTS-V', 'Hybrid', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Yukon XL 1500', '7 Seater', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Sportage', '4x4', 'Kia');
insert into MODEL (model, type, manufacturer) values ('Firefly', '7 Seater', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Festiva', 'Vans & Trucks', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Mustang', 'Hybrid', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Accord', 'Electric', 'Honda');
insert into MODEL (model, type, manufacturer) values ('X5', 'SUV', 'BMW');
insert into MODEL (model, type, manufacturer) values ('626', 'Vans & Trucks', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('V70', 'Vans & Trucks', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('Sable', '4x4', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('Impreza', 'Hatchback', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('XLR', '7 Seater', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Continental GTC', '7 Seater', 'Bentley');
insert into MODEL (model, type, manufacturer) values ('911', '7 Seater', 'Porsche');
insert into MODEL (model, type, manufacturer) values ('SRX', 'Electric', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Savana 3500', '4x4', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Astro', '7 Seater', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Liberty', 'Vans & Trucks', 'Jeep');
insert into MODEL (model, type, manufacturer) values ('Camaro', 'Hybrid', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('XR4Ti', 'Performance', 'Merkur');
insert into MODEL (model, type, manufacturer) values ('tC', 'Hybrid', 'Scion');
insert into MODEL (model, type, manufacturer) values ('MPV', 'Hybrid', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('CX-7', 'Performance', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('S-Class', 'SUV', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Entourage', 'Electric', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Model S', 'Hybrid', 'Tesla');
insert into MODEL (model, type, manufacturer) values ('Dakota', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Monte Carlo', 'Electric', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Hombre', 'Hatchback', 'Isuzu');
insert into MODEL (model, type, manufacturer) values ('Navajo', 'SUV', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Truck', 'Performance', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('A4', 'Performance', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Daewoo Lacetti', 'Hatchback', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Sonoma', 'SUV', 'GMC');
insert into MODEL (model, type, manufacturer) values ('MX-5', '4x4', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Suburban 2500', 'Hatchback', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Ranger', 'Hatchback', 'Ford');
insert into MODEL (model, type, manufacturer) values ('9-7X', 'Vans & Trucks', 'Saab');
insert into MODEL (model, type, manufacturer) values ('Continental Flying Spur', 'Electric', 'Bentley');
insert into MODEL (model, type, manufacturer) values ('Aveo', 'Hatchback', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Altima', '7 Seater', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Equinox', 'Vans & Trucks', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('TundraMax', 'Hatchback', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Montana', 'Performance', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Dakota Club', '4x4', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('xD', 'Vans & Trucks', 'Scion');
insert into MODEL (model, type, manufacturer) values ('4Runner', 'Hybrid', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('GT-R', 'SUV', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Bravada', 'Performance', 'Oldsmobile');
insert into MODEL (model, type, manufacturer) values ('Cougar', 'Vans & Trucks', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('7 Series', 'SUV', 'BMW');
insert into MODEL (model, type, manufacturer) values ('Amanti', 'Performance', 'Kia');
insert into MODEL (model, type, manufacturer) values ('Range Rover', 'Vans & Trucks', 'Land Rover');
insert into MODEL (model, type, manufacturer) values ('Roadmaster', 'Electric', 'Buick');
insert into MODEL (model, type, manufacturer) values ('XC60', 'Hybrid', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('Elantra', '4x4', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Tredia', 'SUV', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('MKX', 'Hybrid', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('M', 'Hybrid', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('Express 1500', 'SUV', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('SL-Class', '4x4', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Q', '7 Seater', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('L300', 'Performance', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('62', 'Hatchback', 'Maybach');
insert into MODEL (model, type, manufacturer) values ('LaCrosse', 'Hybrid', 'Buick');
insert into MODEL (model, type, manufacturer) values ('9-5', 'Electric', 'Saab');
insert into MODEL (model, type, manufacturer) values ('Tiguan', 'Hatchback', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('I', '7 Seater', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('Sunbird', 'Performance', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('4000s', 'SUV', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Boxster', '7 Seater', 'Porsche');
insert into MODEL (model, type, manufacturer) values ('GTI', '4x4', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('Alero', 'Electric', 'Oldsmobile');
insert into MODEL (model, type, manufacturer) values ('Aztek', '7 Seater', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Bonneville', '4x4', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Amigo', 'Performance', 'Isuzu');
insert into MODEL (model, type, manufacturer) values ('QX', 'Electric', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('Corvette', '7 Seater', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Galant', 'SUV', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Sierra 2500', 'Vans & Trucks', 'GMC');
insert into MODEL (model, type, manufacturer) values ('E-Class', '7 Seater', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('240', 'Performance', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('Turbo Firefly', 'Performance', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Mirage', 'SUV', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('B9 Tribeca', 'Electric', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('Intrepid', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Mazda5', '7 Seater', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('X-Type', 'Vans & Trucks', 'Jaguar');
insert into MODEL (model, type, manufacturer) values ('Town Car', '7 Seater', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('DTS', 'Vans & Trucks', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Stratus', '7 Seater', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Fortwo', 'Electric', 'Smart');
insert into MODEL (model, type, manufacturer) values ('RSX', '7 Seater', 'Acura');
insert into MODEL (model, type, manufacturer) values ('M5', 'Hatchback', 'BMW');
insert into MODEL (model, type, manufacturer) values ('C-Class', '4x4', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Rodeo', 'SUV', 'Isuzu');
insert into MODEL (model, type, manufacturer) values ('Pilot', 'Hatchback', 'Honda');
insert into MODEL (model, type, manufacturer) values ('Odyssey', '7 Seater', 'Honda');
insert into MODEL (model, type, manufacturer) values ('Eurovan', '4x4', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('Voyager', 'Performance', 'Chrysler');
insert into MODEL (model, type, manufacturer) values ('9-3', 'SUV', 'Saab');
insert into MODEL (model, type, manufacturer) values ('A8', 'Performance', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Mountaineer', 'Electric', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('Esprit', 'Hybrid', 'Lotus');
insert into MODEL (model, type, manufacturer) values ('Yukon', 'Hatchback', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Tracer', 'Vans & Trucks', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('Miata MX-5', '7 Seater', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Wrangler', 'Hybrid', 'Jeep');
insert into MODEL (model, type, manufacturer) values ('TSX', '7 Seater', 'Acura');
insert into MODEL (model, type, manufacturer) values ('300SL', '7 Seater', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('X6 M', 'Vans & Trucks', 'BMW');
insert into MODEL (model, type, manufacturer) values ('SX4', 'SUV', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('M3', '4x4', 'BMW');
insert into MODEL (model, type, manufacturer) values ('F430', 'Hatchback', 'Ferrari');
insert into MODEL (model, type, manufacturer) values ('Corolla', 'Hatchback', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('X5 M', 'Electric', 'BMW');
insert into MODEL (model, type, manufacturer) values ('Diamante', '7 Seater', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Baja', 'Performance', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('Legacy', '7 Seater', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('S2000', '7 Seater', 'Honda');
insert into MODEL (model, type, manufacturer) values ('300ZX', '7 Seater', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Sonata', '4x4', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Eclipse', 'SUV', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Aerostar', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Aerio', 'Performance', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('S90', 'SUV', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('J', 'SUV', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('Concorde', '7 Seater', 'Chrysler');
insert into MODEL (model, type, manufacturer) values ('370Z', 'Hatchback', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('MR2', '4x4', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Durango', 'SUV', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Tiburon', 'Hybrid', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Excel', '7 Seater', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('TT', '7 Seater', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Toronado', 'Hybrid', 'Oldsmobile');
insert into MODEL (model, type, manufacturer) values ('Vandura 2500', 'Hybrid', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Laser', '4x4', 'Ford');
insert into MODEL (model, type, manufacturer) values ('IS-F', 'SUV', 'Lexus');
insert into MODEL (model, type, manufacturer) values ('Forenza', 'SUV', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Monterey', 'Hybrid', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Charger', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Sierra 3500', '7 Seater', 'GMC');
insert into MODEL (model, type, manufacturer) values ('100', 'Electric', 'Audi');
insert into MODEL (model, type, manufacturer) values ('MDX', '4x4', 'Acura');
insert into MODEL (model, type, manufacturer) values ('ES', '4x4', 'Lexus');
insert into MODEL (model, type, manufacturer) values ('Expedition EL', 'Hybrid', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Ram 3500', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Navigator', 'Vans & Trucks', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('Lucerne', '7 Seater', 'Buick');
insert into MODEL (model, type, manufacturer) values ('TrailBlazer', 'Hatchback', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Cirrus', 'SUV', 'Chrysler');
insert into MODEL (model, type, manufacturer) values ('Silverado', 'Hybrid', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('6 Series', 'Hatchback', 'BMW');
insert into MODEL (model, type, manufacturer) values ('Ram Van 3500', 'Performance', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Sebring', 'Performance', 'Chrysler');
insert into MODEL (model, type, manufacturer) values ('Scirocco', 'Hybrid', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('Excursion', '7 Seater', 'Ford');
insert into MODEL (model, type, manufacturer) values ('6000', '4x4', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Sorento', 'Hybrid', 'Kia');
insert into MODEL (model, type, manufacturer) values ('Mighty Max', 'Performance', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Montero', 'Performance', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Frontier', '7 Seater', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('GS', 'SUV', 'Lexus');
insert into MODEL (model, type, manufacturer) values ('V40', 'Electric', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('Grand Prix', 'SUV', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Sidekick', 'Vans & Trucks', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Silverado 1500', 'Vans & Trucks', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Montego', 'Hatchback', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('Touareg', 'SUV', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('NSX', '7 Seater', 'Acura');
insert into MODEL (model, type, manufacturer) values ('Navigator L', 'Hybrid', 'Lincoln');
insert into MODEL (model, type, manufacturer) values ('S-Series', 'Hybrid', 'Saturn');
insert into MODEL (model, type, manufacturer) values ('929', 'Vans & Trucks', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Challenger', 'Electric', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Colt', 'Vans & Trucks', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Ram Van 2500', 'Electric', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('E-350 Super Duty Van', 'Hatchback', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Prelude', 'Hybrid', 'Honda');
insert into MODEL (model, type, manufacturer) values ('Golf', 'Hybrid', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('L-Series', '4x4', 'Saturn');
insert into MODEL (model, type, manufacturer) values ('E150', 'Hatchback', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Murano', 'Performance', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Storm', 'Vans & Trucks', 'Geo');
insert into MODEL (model, type, manufacturer) values ('Lancer', 'Hatchback', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Tacoma Xtra', '4x4', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Caravan', 'SUV', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Yaris', 'Performance', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Optima', '4x4', 'Kia');
insert into MODEL (model, type, manufacturer) values ('Savana Cargo Van', '7 Seater', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Rally Wagon 2500', 'Performance', 'GMC');
insert into MODEL (model, type, manufacturer) values ('S40', 'Performance', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('LTD Crown Victoria', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Escalade EXT', 'Performance', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Cordia', '4x4', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('Tribeca', '4x4', 'Subaru');
insert into MODEL (model, type, manufacturer) values ('Exige', 'Hatchback', 'Lotus');
insert into MODEL (model, type, manufacturer) values ('Vandura 3500', 'Hatchback', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Park Avenue', 'SUV', 'Buick');
insert into MODEL (model, type, manufacturer) values ('Silhouette', '7 Seater', 'Oldsmobile');
insert into MODEL (model, type, manufacturer) values ('Pajero', 'Hybrid', 'Mitsubishi');
insert into MODEL (model, type, manufacturer) values ('3500', 'Hatchback', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Sonoma Club', 'SUV', 'GMC');
insert into MODEL (model, type, manufacturer) values ('Q7', '7 Seater', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Scoupe', 'Vans & Trucks', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('Five Hundred', '4x4', 'Ford');
insert into MODEL (model, type, manufacturer) values ('900', 'SUV', 'Saab');
insert into MODEL (model, type, manufacturer) values ('DBS', 'SUV', 'Aston Martin');
insert into MODEL (model, type, manufacturer) values ('Patriot', 'Hatchback', 'Jeep');
insert into MODEL (model, type, manufacturer) values ('Firebird Formula', 'Electric', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('Grand Cherokee', '7 Seater', 'Jeep');
insert into MODEL (model, type, manufacturer) values ('Highlander', 'Vans & Trucks', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Journey', 'Vans & Trucks', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('IPL G', '4x4', 'Infiniti');
insert into MODEL (model, type, manufacturer) values ('Z4 M', 'Performance', 'BMW');
insert into MODEL (model, type, manufacturer) values ('Maxima', 'Hatchback', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Jetta', 'Electric', 'Volkswagen');
insert into MODEL (model, type, manufacturer) values ('Diablo', 'Electric', 'Lamborghini');
insert into MODEL (model, type, manufacturer) values ('Lumina', 'SUV', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Ram 2500 Club', '7 Seater', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('B2000', 'Electric', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('80', 'Vans & Trucks', 'Audi');
insert into MODEL (model, type, manufacturer) values ('F-Series Super Duty', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Land Cruiser', 'Hybrid', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('Ram Wagon B150', 'Hybrid', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Protege', 'Vans & Trucks', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('CTS', 'Electric', 'Cadillac');
insert into MODEL (model, type, manufacturer) values ('Suburban', 'Vans & Trucks', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Grand Am', 'Hatchback', 'Pontiac');
insert into MODEL (model, type, manufacturer) values ('SC', '7 Seater', 'Lexus');
insert into MODEL (model, type, manufacturer) values ('600SEL', '7 Seater', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Legend', '7 Seater', 'Acura');
insert into MODEL (model, type, manufacturer) values ('Ghost', 'Electric', 'Rolls-Royce');
insert into MODEL (model, type, manufacturer) values ('Grand Marquis', '4x4', 'Mercury');
insert into MODEL (model, type, manufacturer) values ('XC70', 'SUV', 'Volvo');
insert into MODEL (model, type, manufacturer) values ('Avalon', 'Hatchback', 'Toyota');
insert into MODEL (model, type, manufacturer) values ('F-Series', '4x4', 'Ford');
insert into MODEL (model, type, manufacturer) values ('XJ Series', '7 Seater', 'Jaguar');
insert into MODEL (model, type, manufacturer) values ('Quattroporte', '7 Seater', 'Maserati');
insert into MODEL (model, type, manufacturer) values ('Avalanche 1500', 'Performance', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('CX-9', 'SUV', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Kizashi', 'Electric', 'Suzuki');
insert into MODEL (model, type, manufacturer) values ('Escape', 'Hatchback', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Countach', 'SUV', 'Lamborghini');
insert into MODEL (model, type, manufacturer) values ('Econoline E150', 'Vans & Trucks', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Lightning', '4x4', 'Ford');
insert into MODEL (model, type, manufacturer) values ('Crown Victoria', 'Performance', 'Ford');
insert into MODEL (model, type, manufacturer) values ('H3', 'Performance', 'Hummer');
insert into MODEL (model, type, manufacturer) values ('Cavalier', 'Hybrid', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('X3', 'Electric', 'BMW');
insert into MODEL (model, type, manufacturer) values ('Crossfire', '7 Seater', 'Chrysler');
insert into MODEL (model, type, manufacturer) values ('Rodeo Sport', 'Electric', 'Isuzu');
insert into MODEL (model, type, manufacturer) values ('Ram 1500 Club', 'Hatchback', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('600SL', 'Vans & Trucks', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Grand Voyager', 'Hatchback', 'Plymouth');
insert into MODEL (model, type, manufacturer) values ('SLK55 AMG', 'Performance', 'Mercedes-Benz');
insert into MODEL (model, type, manufacturer) values ('Colorado', '4x4', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Aries', 'Hatchback', 'Dodge');
insert into MODEL (model, type, manufacturer) values ('Impala SS', 'Electric', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('S10', '7 Seater', 'Chevrolet');
insert into MODEL (model, type, manufacturer) values ('Rogue', 'Hatchback', 'Nissan');
insert into MODEL (model, type, manufacturer) values ('Impulse', 'Electric', 'Isuzu');
insert into MODEL (model, type, manufacturer) values ('164', 'Hybrid', 'Alfa Romeo');
insert into MODEL (model, type, manufacturer) values ('XG350', 'Vans & Trucks', 'Hyundai');
insert into MODEL (model, type, manufacturer) values ('5000CS Quattro', '7 Seater', 'Audi');
insert into MODEL (model, type, manufacturer) values ('Mazda3', 'Electric', 'Mazda');
insert into MODEL (model, type, manufacturer) values ('Cooper', 'Vans & Trucks', 'MINI');
insert into MODEL (model, type, manufacturer) values ('Camry', 'Vans & Trucks', 'Toyota');