insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Mekele', 'Ethiopia', 'Carberry', 9141099782, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (71, 'Sao Joao dos Patos', 'Brazil', 'Jana', 29067441591, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (434, 'Pakenjeng', 'Indonesia', 'Lakewood Gardens', 83400785363, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Ocongate', 'Peru', 'Sachs', 10585180918, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (680, 'Sabbah', 'Syria', 'Esker', 21259783499, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (667, 'Brikama Nding', 'Gambia', 'Westport', 73024398422, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (835, 'Farsta', 'Sweden', 'Washington', 45624153616, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (922, 'Puan', 'Argentina', 'Summerview', 79513824259, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (7, 'Xarre', 'Albania', 'Wayridge', 29741941658, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (452, 'Deranitan', 'Indonesia', 'Schurz', 7661565307, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Frontignan', 'France', 'Sunbrook', 47159016040, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (481, 'Bechlin', 'Czech Republic', 'Hoepker', 75564947687, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (376, 'Mache', 'Peru', 'Vahlen', 37325211851, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (665, 'Eksjo', 'Sweden', 'Anthes', 60785638318, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (993, 'Suita', 'Japan', 'Sachtjen', 25176390104, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (996, 'Serh', 'China', 'Prentice', 82016819409, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (651, 'Dagou', 'China', 'Bashford', 41416449918, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (299, 'Hita', 'Japan', 'Cherokee', 70513482045, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (153, 'Chengnan', 'China', 'Lien', 58129409028, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (190, 'Kumalarang', 'Philippines', 'Tennyson', 97756191762, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (645, 'Takanosu', 'Japan', 'Reindahl', 34706049359, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (676, 'Novi Itebej', 'Serbia', 'Garrison', 1881286902, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (360, 'Anicuns', 'Brazil', 'Superior', 59070743893, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (401, 'Daeosin Satu', 'Indonesia', 'Kim', 43383429654, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (646, 'Cirangrang', 'Indonesia', 'Annamark', 88798036470, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (519, 'Changsheng', 'China', 'Walton', 11633050669, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (796, 'Pakis', 'Indonesia', 'Heffernan', 37615450800, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (591, 'Nancy', 'France', 'Autumn Leaf', 47282907521, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (142, 'Malabar', 'Indonesia', 'Evergreen', 52239848684, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (319, 'Pancoran', 'Indonesia', 'Anderson', 95509060738, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (432, 'Liangkou', 'China', 'Prairie Rose', 57374652520, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (870, 'Badu', 'China', 'Moose', 52733275561, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (80, 'Codajas', 'Brazil', 'Anhalt', 18601119505, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (228, 'Annecy', 'France', 'Menomonie', 5596144942, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (700, 'Hannō', 'Japan', 'Little Fleur', 11904831041, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (658, 'Maqian', 'China', 'Eagan', 33016692570, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (868, 'Xukou', 'China', 'Ohio', 84834630757, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Pringgabaya', 'Indonesia', 'Westport', 36325257246, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (36, 'Costa Nova do Prado', 'Portugal', 'Mcguire', 49982984038, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (99, 'Nularan', 'Indonesia', 'Victoria', 20462401002, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Dulles', 'United States', 'Continental', 85331562078, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (421, 'Marneuli', 'Georgia', 'Beilfuss', 35892228260, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (935, 'Ngozi', 'Burundi', 'Bluestem', 98324046038, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (880, 'Uppsala', 'Sweden', 'Declaration', 91393253295, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (927, 'Fresno', 'United States', 'Pond', 43692788269, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (108, 'Xibing', 'China', 'Hauk', 56422707077, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Larnaca', 'Cyprus', 'Quincy', 70282896480, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (465, 'Verkhnya Rozhanka', 'Ukraine', 'Northridge', 39585246795, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (938, 'Lenger', 'Kazakhstan', 'Spohn', 38237194127, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (337, 'Zarechnyy', 'Russia', 'Blaine', 45174735129, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (852, 'Kolape', 'Philippines', 'Carpenter', 16177106748, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (201, 'Áno Kalentíni', 'Greece', 'Thompson', 9305998342, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (329, 'Simuay', 'Philippines', 'Cascade', 28980850539, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (850, 'Tippi', 'Ethiopia', 'Scott', 37303948810, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (603, 'Torzhok', 'Russia', 'Menomonie', 851546607, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (809, 'Al Farwānīyah', 'Kuwait', 'Eastwood', 56500429545, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (486, 'Las Varas', 'Argentina', 'Beilfuss', 77369872904, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (214, 'Barrio San Luis', 'Colombia', 'Mariners Cove', 62586584844, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (536, 'Vokhaïkó', 'Greece', 'Montana', 82962799526, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (669, 'Milówka', 'Poland', 'Westport', 8439713888, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (525, 'Raci Kulon', 'Indonesia', 'Mesta', 98412062189, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (9, 'Cavaillon', 'France', 'Bowman', 98558092213, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (940, 'Tangnan', 'China', 'Delladonna', 80493296688, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (420, 'Acobamba', 'Peru', 'Talisman', 75472638756, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (267, 'Przyborów', 'Poland', 'Mayfield', 44124038539, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (313, 'Tartaro', 'Philippines', 'Novick', 67664010299, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (474, 'Hodkovičky', 'Czech Republic', 'Tony', 15776845651, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (318, 'Lamas', 'Portugal', 'Logan', 76109882214, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (290, 'Aduo', 'China', 'Cottonwood', 47616219080, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (200, 'Tangtu', 'China', 'Lien', 74469481490, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (596, 'Ujiie', 'Japan', 'Dakota', 44210195211, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (728, 'München', 'Germany', 'Debs', 11841409823, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (317, 'Azua', 'Dominican Republic', 'Kensington', 47239562895, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (162, 'Al Ḩashwah', 'Yemen', 'Warrior', 43184702946, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (929, 'Molo', 'Kenya', 'Pankratz', 74935428430, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (686, 'Tetyushi', 'Russia', 'Anzinger', 52056075267, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (370, 'Dindima', 'Nigeria', 'Old Shore', 55305935343, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (580, 'Narong', 'China', 'Commercial', 69944797424, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (962, 'Nong Chik', 'Thailand', 'Garrison', 77725715542, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Kaoma', 'Zambia', 'Crescent Oaks', 50096613009, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (872, 'Mangkon Daja', 'Indonesia', 'Annamark', 58117912601, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (204, 'Lafayette', 'United States', 'Stone Corner', 48591843822, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (983, 'Sherbrooke', 'Canada', 'Lakewood Gardens', 91585273168, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (504, 'Lazaro Cardenas', 'Mexico', 'Scoville', 9753762985, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (18, 'Petrozavodsk', 'Russia', 'Pankratz', 34140829293, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (840, 'Pangligaran', 'Indonesia', 'Eagan', 11772376579, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (631, 'Hisings Kärra', 'Sweden', 'Bayside', 70540970646, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (861, 'Banjar Mambalkajanan', 'Indonesia', 'Orin', 33234716577, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (696, 'Beiqiao', 'China', 'Towne', 41616512833, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (472, 'Jevíčko', 'Czech Republic', 'Dunning', 4249773090, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (86, 'Hougong', 'China', 'Cherokee', 67656627449, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (433, 'Owerri', 'Nigeria', 'Esker', 57593722374, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (373, 'Ouzini', 'Comoros', 'Daystar', 12522317348, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (780, 'Cachachi', 'Peru', 'Ruskin', 71351252740, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (498, 'Karangora', 'Indonesia', 'Jackson', 30553663736, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (547, 'Anoek', 'Indonesia', 'Ilene', 52333757049, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (418, 'Guradog', 'Indonesia', 'Rockefeller', 39458716824, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (117, 'Rancakuya', 'Indonesia', 'Maryland', 69047261307, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (550, 'Rogongon', 'Philippines', 'Sunfield', 99497580706, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (874, 'Limbaži', 'Latvia', 'Burning Wood', 67843940925, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (241, 'Masalovka', 'Russia', 'Merchant', 55809521983, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (463, 'Espinosa', 'Brazil', 'Fuller', 38216380999, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (460, 'Liulin', 'China', 'Eagan', 41931410799, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (941, 'Aiánteio', 'Greece', 'Hoffman', 20993334279, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (43, 'Mayong', 'Indonesia', 'Shelley', 87939696282, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (718, 'Anadia', 'Portugal', 'Jenna', 20178320407, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (273, 'Cilentung', 'Indonesia', 'Sutherland', 70059528075, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (284, 'Vatutino', 'Russia', 'South', 19762062628, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (24, 'Conima', 'Peru', 'Thackeray', 32319029028, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (519, 'Aubergenville', 'France', 'Lakeland', 17534675152, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (618, 'Maluanluan', 'Philippines', 'Aberg', 32913146462, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (461, 'Vesoul', 'France', 'Main', 16704685077, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (287, 'Changsha', 'China', 'Lunder', 94799698718, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (179, 'Santa Venera', 'Malta', 'Sachtjen', 29998704417, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (449, 'Semang', 'Indonesia', 'Meadow Vale', 88459364836, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (605, 'Geji', 'China', 'Warner', 20813078032, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Litibakul', 'Indonesia', 'Northport', 59258430628, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (678, 'Changgucheng', 'China', 'Merrick', 2310982232, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (90, 'Kebon', 'Indonesia', 'Scofield', 57246955848, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (894, 'Pavshino', 'Russia', 'Northport', 57214348614, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (489, 'Cartagena del Chairá', 'Colombia', 'Montana', 4601444704, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (889, 'Salgado', 'Brazil', 'Vahlen', 2329715437, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (878, 'Timaru', 'New Zealand', 'Ridge Oak', 69854730377, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (908, 'Mingjiu', 'China', 'Nelson', 73277128272, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (235, 'Centre de Flacq', 'Mauritius', 'Kim', 2542508452, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (419, 'Guanqing', 'China', 'Loeprich', 24624701369, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (86, 'Atyrau', 'Kazakhstan', 'Banding', 90416921293, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (295, 'Panalanoy', 'Philippines', 'La Follette', 25747157275, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (912, 'Phunphin', 'Thailand', 'Memorial', 90039502734, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (447, 'Могила', 'Macedonia', 'Northview', 84747177140, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (585, 'Dongfu', 'China', 'Sutteridge', 54254388363, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (218, 'Krzęcin', 'Poland', 'Kinsman', 97621435688, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (55, 'Aimadamodo', 'Indonesia', 'Eagan', 1951126876, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (182, 'Amiens', 'France', 'Lindbergh', 48840489600, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (344, 'La Asunción', 'Costa Rica', 'Rowland', 96185329912, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Hohoe', 'Ghana', 'Del Sol', 53244483104, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (87, 'Athi River', 'Kenya', 'Village', 1518435193, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (945, 'Betaf', 'Indonesia', 'Comanche', 7222205414, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (849, 'Pasirmukti', 'Indonesia', 'Becker', 87528023214, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (862, 'Citeureup', 'Indonesia', 'Manufacturers', 69350692146, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (654, 'Boguszów-Gorce', 'Poland', 'Montana', 83782296239, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (441, 'Ndélé', 'Central African Republic', 'Brickson Park', 46207518378, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (794, 'Quyangqiao', 'China', 'Montana', 9804445766, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (198, 'Lazi', 'Ukraine', 'Farragut', 43217365941, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (919, 'Betzdorf', 'Luxembourg', 'Lighthouse Bay', 897009407, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (735, 'Tayabamba', 'Peru', 'Division', 95995128719, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (70, 'Chenfang', 'China', 'Merry', 33845082890, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (70, 'Miguel Hidalgo', 'Mexico', 'Village', 51337701842, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (626, 'Les Coteaux', 'Canada', 'Vera', 33312661854, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (937, 'Boquira', 'Brazil', 'Gina', 51586459263, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (947, 'Shache', 'China', 'Northview', 66090181409, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (1000, 'San Martín', 'Argentina', '6th', 92387315100, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (438, 'Wangkung', 'Indonesia', 'Doe Crossing', 78084776717, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (493, 'Hlybokaye', 'Belarus', 'Esch', 23469395979, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (570, 'Cergy-Pontoise', 'France', 'Manley', 485685819, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (171, 'Sagrada Familia', 'Philippines', 'Tony', 59207372698, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (416, 'Putrajaya', 'Malaysia', 'Michigan', 68893042415, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (353, 'Terenozek', 'Kazakhstan', 'Myrtle', 98432343798, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Sundsvall', 'Sweden', 'Delaware', 61590985335, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (118, 'Baturité', 'Brazil', 'Arizona', 53776084151, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Tangga', 'Indonesia', 'Main', 7767779834, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (174, 'Wonokerso', 'Indonesia', 'Stephen', 2601514750, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (704, 'Salgar', 'Colombia', 'Atwood', 56300612368, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (701, 'Pytalovo', 'Russia', 'Darwin', 38911638805, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (641, 'Huambo', 'Angola', 'Eagan', 9056840647, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (629, 'Dolní Kounice', 'Czech Republic', 'North', 37325634184, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (899, 'Xufu', 'China', 'Moose', 96478383247, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (906, 'San Quintin', 'Philippines', 'Twin Pines', 68412571834, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (542, 'Ciodeng', 'Indonesia', 'Hazelcrest', 53588765436, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (745, 'Toledo', 'United States', 'Sutteridge', 33723241163, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (643, 'Katabu', 'Indonesia', 'Jenifer', 42813853442, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (708, 'Muqui', 'Peru', 'Oxford', 11049012178, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (480, 'Leeuwarden', 'Netherlands', 'Coleman', 17982677289, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (606, 'Sanlicheng', 'China', 'Dahle', 11739952549, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (931, 'Bomadi', 'Nigeria', 'Anthes', 68060082133, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (183, 'Baltimore', 'United States', 'Vera', 27906725516, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Sexiong', 'China', 'Nelson', 84788617193, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (978, 'Rey', 'Iran', 'Corben', 83074909735, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (361, 'Tournon-sur-Rhône', 'France', 'Donald', 11761530415, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (889, 'Chunhu', 'China', 'Lighthouse Bay', 11244632166, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (398, 'Hongkou', 'China', 'Vera', 70323677259, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (469, 'Meukek', 'Indonesia', 'Manitowish', 26627262346, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (682, 'Lisewo', 'Poland', 'Pennsylvania', 40074574527, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (504, 'Jega', 'Nigeria', 'Marcy', 13893249576, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (286, 'Kasreman', 'Indonesia', 'Carpenter', 5267021217, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (721, 'Qiaonan', 'China', 'Ridge Oak', 84624627954, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Saguing', 'Philippines', 'Katie', 36807599655, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (830, 'Saskatoon', 'Canada', 'Dryden', 58192489310, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (955, 'Sa‘sa‘', 'Syria', 'Swallow', 61744501566, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (964, 'Nichinan', 'Japan', 'Basil', 56734475658, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (904, 'Zawichost', 'Poland', 'School', 58489801221, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (747, 'Lakeland', 'United States', 'High Crossing', 1322658465, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (844, 'Colmar', 'France', 'Michigan', 30008869735, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (880, 'Gwaram', 'Nigeria', 'Carioca', 79754316232, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (817, 'Chernelytsya', 'Ukraine', 'Monument', 56755727969, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (383, 'Aveiras de Cima', 'Portugal', 'Buena Vista', 22095579801, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (688, 'El Zapote', 'Mexico', 'Fairfield', 82347961513, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (992, 'Kohtla-Järve', 'Estonia', 'Bunker Hill', 88613179843, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (87, 'Khairpur', 'Pakistan', 'Hallows', 86532464834, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (371, 'Bavorov', 'Czech Republic', 'Scott', 71470235069, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (863, 'Zongzhai', 'China', 'Truax', 50578108914, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (993, 'Phù Mỹ', 'Vietnam', 'Montana', 65874319689, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Xujiafang', 'China', 'Almo', 91640169000, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (3, 'Jelat', 'Indonesia', 'Declaration', 33151714748, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (424, 'Dieppe', 'France', 'Ridge Oak', 65227507783, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (334, 'Hondo Valle', 'Dominican Republic', 'Blue Bill Park', 16305212105, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (145, 'Koror Town', 'Palau', 'Morning', 4576769908, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (655, 'Lais', 'Philippines', 'Fair Oaks', 9987230616, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Zhubei', 'Taiwan', 'Loomis', 19840680826, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (642, 'Pittsburgh', 'United States', 'Commercial', 5303522200, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (559, 'Nizhniy Bestyakh', 'Russia', 'Scofield', 28160425884, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (495, 'Yanyang', 'China', '6th', 1196899830, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Bijia', 'China', 'Vahlen', 82354287804, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (971, 'El Parco District', 'Peru', 'Bartelt', 54924076922, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (547, 'Springbok', 'South Africa', 'Muir', 98217960921, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (681, 'Salgado', 'Brazil', 'Heath', 47216184045, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (732, 'Chwałowice', 'Poland', 'Mallard', 79864657777, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (348, 'Paratinga', 'Brazil', '1st', 6260580625, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (427, 'Da’an', 'China', 'Pleasure', 34577250309, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (92, 'Namling', 'China', 'Pierstorff', 88146204912, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (783, 'Gävle', 'Sweden', 'Summer Ridge', 49926652071, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (140, 'Psáry', 'Czech Republic', 'Erie', 96423028139, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (136, 'Brochów', 'Poland', 'Fairview', 18416675913, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (510, 'San Francisco', 'Mexico', 'Aberg', 43474074946, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (785, 'Ulaandel', 'Mongolia', 'Hallows', 71880040133, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (753, 'Ash Shaḩānīyah', 'Qatar', 'Valley Edge', 11032646146, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Ponta Delgada', 'Portugal', 'Spenser', 57384416751, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (804, 'Tabalosos', 'Peru', 'Vernon', 40007692607, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (804, 'Geshan', 'China', 'Ohio', 46774661864, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (887, 'Smokvica', 'Croatia', 'Southridge', 50494527106, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (675, 'Ýdra', 'Greece', 'Pepper Wood', 74768374060, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (458, 'Presidente Prudente', 'Brazil', 'Pine View', 77786347965, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (392, 'Ponte da Pedra', 'Portugal', 'Main', 77939712401, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (803, 'Leles', 'Indonesia', 'Stang', 89914639945, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (674, 'Changkeng', 'China', 'Hintze', 14980554797, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (419, 'Ruda-Huta', 'Poland', 'Scott', 84223139477, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (590, 'Blois', 'France', 'Summer Ridge', 86216942150, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (263, 'Banjar Sebual', 'Indonesia', 'Mifflin', 55294262602, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (407, 'Quetigny', 'France', 'Elmside', 52565175436, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (221, 'Gaoping', 'China', 'North', 77089277538, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (588, 'Zhangbagou', 'China', 'Prentice', 89659556085, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (129, 'Ar Ru’ays', 'Qatar', 'Westridge', 4694917707, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (875, 'Karmah an Nuzul', 'Sudan', 'Vahlen', 10298365131, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (366, 'Fucheng', 'China', 'Granby', 47328705541, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (980, 'Plaški', 'Croatia', 'Meadow Vale', 47464241673, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (285, 'Villa Florida', 'Paraguay', 'Springview', 62626921236, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (500, 'Krajan Sale', 'Indonesia', 'Mesta', 12704241256, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (973, 'Gammad', 'Philippines', 'David', 96461718306, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (68, 'Kajatian', 'Philippines', 'Towne', 90479079409, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (447, 'Kiihtelysvaara', 'Finland', 'Sunbrook', 39658954374, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (744, 'Santo Niño', 'Philippines', 'Merrick', 37174421161, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (753, 'Bahāwalpur', 'Pakistan', 'Jenna', 63921504645, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (180, 'Cervantes', 'Philippines', 'Scofield', 53935898240, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (670, 'Stockholm', 'Sweden', 'Sundown', 43659951379, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (885, 'Sunne', 'Sweden', 'Ryan', 87681932593, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (93, 'Pedinó', 'Greece', 'Colorado', 47365069408, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (507, 'Melioratyvne', 'Ukraine', 'Heffernan', 11707194970, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (63, 'Klenak', 'Serbia', 'Ramsey', 63466090819, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (194, 'Firovo', 'Russia', 'Eastwood', 89707241491, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (493, 'Nandasmo', 'Nicaragua', 'Nelson', 54285308164, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (792, 'Curiapo', 'Venezuela', 'Pleasure', 73998751815, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (679, 'Botshabelo', 'South Africa', 'Clemons', 82365185671, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (644, 'Baisha', 'China', 'High Crossing', 53701848860, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (954, 'Sabi', 'Gambia', 'Shopko', 25609153418, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (44, 'Viekšniai', 'Lithuania', 'Vermont', 15163020245, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (833, 'Heping', 'China', 'Pawling', 90217634259, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (356, 'Mosteiros', 'Portugal', 'Hansons', 58672342719, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (739, 'Grahamstown', 'South Africa', 'Autumn Leaf', 19939548357, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (995, 'Taiping', 'China', 'Dapin', 79045970892, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (76, 'Zhouxi', 'China', 'Tony', 30844905404, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (592, 'Sestroretsk', 'Russia', 'Westport', 7633415271, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (37, 'Armenia', 'Colombia', 'Ramsey', 16205966318, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (766, 'Porteirinha', 'Brazil', 'Crowley', 58276960987, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (102, 'Paraíso', 'Portugal', 'Oxford', 81118583316, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (496, 'Rukunlima Bawah', 'Indonesia', 'Jay', 55721252049, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (788, 'Nancheng', 'China', 'Memorial', 85929500962, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (220, 'Barrhead', 'Canada', 'Kennedy', 44935652317, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (363, 'Chishtiān Mandi', 'Pakistan', 'Vermont', 35978730636, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (749, 'Bussum', 'Netherlands', 'Oriole', 9965910292, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (262, 'Las Higueras', 'Argentina', 'Park Meadow', 55744773317, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (276, 'Gafsa', 'Tunisia', 'Pawling', 55000663617, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (325, 'Gupakan', 'Indonesia', 'Novick', 9760749017, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (621, 'Nancha', 'China', 'Upham', 94456084345, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (291, 'Calimita', 'Colombia', 'Muir', 33456032998, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (702, 'Resistencia', 'Argentina', 'School', 54787295210, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (222, 'Gornyy', 'Russia', 'Sycamore', 44751249572, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (517, 'Tapada das Mercês', 'Portugal', 'Annamark', 47834964916, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (659, 'Gornja Koprivna', 'Bosnia and Herzegovina', 'Independence', 52029493528, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (743, 'Taypano', 'Philippines', 'Chinook', 21081259562, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (513, 'Puhechang', 'China', 'Chive', 17890287418, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (161, 'Villanueva', 'Philippines', 'Gale', 91772108338, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (373, 'Dupnitsa', 'Bulgaria', 'Tennyson', 60080868753, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (945, 'Biała', 'Poland', 'Raven', 93004828574, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (534, 'Licheng', 'China', 'Aberg', 42579229081, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (690, 'Karatsu', 'Japan', 'Gateway', 11432792147, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (236, 'Saint-Amand-les-Eaux', 'France', 'Pond', 3382992431, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (755, 'Santa Maria do Souto', 'Portugal', 'Marcy', 92947865444, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (344, 'Little Rock', 'United States', 'Del Mar', 32589639403, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (924, 'Fresnes', 'France', 'Manitowish', 66186061760, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (295, 'Luniao', 'China', 'Delladonna', 49811411930, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (10, 'Göteborg', 'Sweden', 'Sunnyside', 88611185551, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (831, 'Madalum', 'Philippines', 'Scofield', 16590292175, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (82, 'Kandana', 'Sri Lanka', 'Arizona', 52855833571, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (468, 'Zhongshi', 'China', 'Sage', 50169937491, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (773, 'Karjalohja', 'Finland', 'Redwing', 8949034100, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (3, 'Mozdok', 'Russia', 'Manitowish', 22564072391, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (926, 'Chvaletice', 'Czech Republic', 'Carpenter', 10059238422, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Vřesina', 'Czech Republic', 'Twin Pines', 97294012972, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (646, 'Shiozawa', 'Japan', 'Huxley', 66923847195, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (685, 'Göteborg', 'Sweden', 'Granby', 67015170322, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (831, 'Raemude', 'Indonesia', 'Badeau', 11781539796, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (341, 'Nūrābād', 'Iran', 'Clyde Gallagher', 72628767291, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (690, 'Rislane', 'Morocco', 'Hoepker', 44825217049, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (985, 'Atsipópoulon', 'Greece', 'New Castle', 12195443268, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (274, 'Loum', 'Cameroon', 'Kinsman', 14981690505, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (677, 'Jingnao', 'China', 'Montana', 35538426277, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (613, 'Santa Fé do Sul', 'Brazil', 'Southridge', 93989228994, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (306, 'Odintsovo', 'Russia', 'Mallard', 21438046482, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (479, 'Atlanta', 'United States', 'Nancy', 28347809370, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (206, 'Semuda', 'Indonesia', 'Melrose', 2623368868, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (386, 'Zharkent', 'Kazakhstan', 'Quincy', 97701348226, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (156, 'Gunung Talang', 'Indonesia', 'Londonderry', 12514703094, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Paso de Indios', 'Argentina', 'Kenwood', 15595298704, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (393, 'Rahama', 'Nigeria', 'Gina', 7265757162, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (197, 'Palmira', 'Cuba', 'Farragut', 79906841612, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Castañas', 'Philippines', 'Dakota', 27974979315, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (382, 'Caridade', 'Portugal', 'Rowland', 74184218773, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (541, 'Scholkine', 'Ukraine', 'Esker', 29723221013, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Demuk', 'Indonesia', 'Pankratz', 50596327191, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (729, 'Kurbnesh', 'Albania', 'Golf Course', 49174984766, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Perez', 'Philippines', 'Mosinee', 49572093885, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (49, 'Nianyushan', 'China', 'Meadow Ridge', 33216892186, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (321, 'Barra', 'Brazil', 'Stephen', 25224703659, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Issa', 'Russia', 'Waywood', 96408925804, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (206, 'Daxin', 'China', 'Straubel', 65849802223, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (543, 'Sukadana', 'Indonesia', 'Londonderry', 7834634324, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Atabayan', 'Philippines', 'Susan', 45768177680, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (835, 'Marco', 'Brazil', 'Beilfuss', 97680356881, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (470, 'Bejucal', 'Cuba', 'Thackeray', 77383803888, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (7, 'Soanierana Ivongo', 'Madagascar', 'Butterfield', 74316628080, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (346, 'Storozhevaya', 'Russia', 'South', 44721140627, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (716, 'Tiro', 'Indonesia', 'Corry', 28642727486, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (200, 'Novolugovoye', 'Russia', 'Sherman', 98210445315, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (641, 'Soa', 'Indonesia', 'Jenna', 82168050775, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (309, 'Narbonne', 'France', 'Cottonwood', 55339442314, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Nurota Shahri', 'Uzbekistan', 'Warbler', 20856386058, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (805, 'Niš', 'Serbia', 'Weeping Birch', 63896094590, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (524, 'Arras', 'France', 'Tennyson', 98723508572, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (527, 'Kangping', 'China', 'Bashford', 16963019986, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (451, 'Runting', 'Indonesia', 'Mendota', 59578822199, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (343, 'Przystajń', 'Poland', 'Sage', 23617414328, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (410, 'Pedro Leopoldo', 'Brazil', 'Lawn', 10398288382, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (699, 'Beaumont', 'Canada', 'Mandrake', 93881285472, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (922, 'Malishka', 'Armenia', 'David', 58409958276, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (145, 'Isyangulovo', 'Russia', 'Holy Cross', 6846555386, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (758, 'João Pessoa', 'Brazil', 'Fair Oaks', 82263693384, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (127, 'Yeysk', 'Russia', 'Reinke', 26048188152, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (210, 'Rrasa e Sipërme', 'Albania', 'Anthes', 92414944133, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (563, 'Gornje Živinice', 'Bosnia and Herzegovina', 'Ridgeway', 54168744652, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (770, 'Grenoble', 'France', 'Park Meadow', 69970323363, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (467, 'Ajaccio', 'France', 'Prairieview', 90824066619, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (265, 'El Guapinol', 'Honduras', 'Upham', 66270037530, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (406, 'Sim', 'Russia', 'Ryan', 1166949996, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (925, 'Abū Mūsā', 'Iran', 'Armistice', 27711060540, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (248, 'Guangning', 'China', 'Northview', 6054559347, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (345, 'Wang Saphung', 'Thailand', 'Waxwing', 84402870564, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (369, 'General Alvear', 'Argentina', 'Arrowood', 92329258742, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (907, 'Villavicencio', 'Colombia', 'Dorton', 59277334278, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (528, 'Camino Real', 'Mexico', 'Amoth', 33663676594, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (260, 'Karsin', 'Poland', 'La Follette', 24851642917, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (349, 'Farīdpur', 'Bangladesh', 'Northland', 94881793116, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'Thị Trấn Quảng Uyên', 'Vietnam', 'Hazelcrest', 46160385689, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (903, 'Zabaykal’sk', 'Russia', '1st', 14339121852, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (995, 'Paipa', 'Colombia', 'Elka', 1285587810, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (450, 'São Tomé', 'Portugal', 'Eliot', 55083332029, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (877, 'Hollola', 'Finland', 'Village', 29975968208, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (183, 'Xingzhen', 'China', 'Gina', 17719320415, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (752, 'Krasnyy Yar', 'Russia', 'Stoughton', 16931936107, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (153, 'Kiukasen', 'Indonesia', 'Dahle', 16237133122, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (420, 'Rochester', 'United States', 'Hagan', 14613159188, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (259, 'Melaka', 'Malaysia', 'Farwell', 85735219943, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (512, 'Tarasovskiy', 'Russia', 'Green', 12798387, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (82, 'Aş Şūrah aş Şaghīrah', 'Syria', 'Nancy', 52318093201, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (192, 'Gibsons', 'Canada', 'Oxford', 12682671823, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (37, 'Sanlicheng', 'China', 'Fremont', 56816939861, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (589, 'Marly-le-Roi', 'France', 'Merry', 56117695110, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (352, 'Inđija', 'Serbia', 'Lyons', 32825647291, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (475, 'Mirecourt', 'France', 'Sunfield', 9167971159, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (304, 'Peicheng', 'China', 'Warrior', 18674981131, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (984, 'Yuejin', 'China', 'Blackbird', 82037325282, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (478, 'Puksoozero', 'Russia', 'Pleasure', 34976722214, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (233, 'Gupakan', 'Indonesia', 'Bultman', 18040807747, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (270, 'Siguiri', 'Guinea', 'Blaine', 25301651900, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (747, 'Panshan', 'China', 'David', 3728413447, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (961, 'Onsala', 'Sweden', 'Hansons', 18636596957, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Moorreesburg', 'South Africa', 'Mesta', 16831520681, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (691, 'Akron', 'United States', 'Grim', 6253350299, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (837, 'Štore', 'Slovenia', 'Dennis', 17304319546, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (502, 'Neepawa', 'Canada', 'Scoville', 29218445027, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (759, 'Tomilino', 'Russia', 'Summerview', 7246748140, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (538, 'Macachín', 'Argentina', 'Fallview', 76801409213, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (514, 'Glugu', 'Indonesia', 'Golf View', 32156184546, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (904, 'Prince Rupert', 'Canada', 'Ridge Oak', 8177007740, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (71, 'Ocuviri', 'Peru', 'Blackbird', 18650360354, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (459, 'Nanyue', 'China', 'Paget', 2868609330, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (982, 'Huangjin', 'China', 'Swallow', 12290620184, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'Yangsan', 'South Korea', 'Alpine', 2003421303, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (165, 'Yanahuaya', 'Peru', 'Transport', 69539805599, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (668, 'Athlone', 'Ireland', 'Erie', 32254769600, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (917, 'Hanlin', 'China', 'Clyde Gallagher', 17952356184, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (801, 'Duqu', 'China', 'La Follette', 55205614236, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (425, 'Villa Nueva', 'Honduras', 'Fairfield', 56621046310, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (252, 'Shiqiao', 'China', 'Barnett', 64405124291, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (566, 'Budapest', 'Hungary', 'Nancy', 19329015416, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (94, 'Asquipata', 'Peru', 'Corry', 9572650210, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (435, 'Oehaunu', 'Indonesia', 'Lyons', 83379526734, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (839, 'Tsotsin-Yurt', 'Russia', 'Holy Cross', 9413971631, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (543, 'Gómez', 'Panama', 'Porter', 95249429821, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (914, 'Imeni Babushkina', 'Russia', 'Ilene', 40491492302, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (108, 'Tankhoy', 'Russia', 'Meadow Ridge', 54045803808, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (825, 'Dobre', 'Poland', 'Independence', 14790342382, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Baro Kunda', 'Gambia', 'Continental', 62489909898, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (168, 'Oświęcim', 'Poland', 'Florence', 72044827258, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (5, 'Krajanpagowan', 'Indonesia', 'Mosinee', 96176964898, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (654, 'Santa Rita Aplaya', 'Philippines', 'Dryden', 73344844018, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (784, 'Legok', 'Indonesia', 'Trailsway', 15452701517, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (767, 'Weizhou', 'China', 'Myrtle', 41014336509, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (8, 'Vila do Maio', 'Cape Verde', 'Meadow Ridge', 96584519483, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (307, 'Duqu', 'China', 'Montana', 62045608944, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (795, 'Washington', 'United States', 'Vidon', 38587645307, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (962, 'Los Aquijes', 'Peru', 'Swallow', 65674183496, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (150, 'La Libertad', 'Honduras', 'International', 61557326710, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (731, 'Guaxupé', 'Brazil', 'Muir', 33056987866, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (527, 'Qingfenglin', 'China', 'Michigan', 77443926613, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (989, 'Pisões', 'Portugal', 'Sage', 18302460090, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (416, 'Krasnodar', 'Russia', 'Myrtle', 35891849879, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (697, 'Götene', 'Sweden', 'Troy', 77542304876, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (537, 'Quilmaná', 'Peru', 'Mesta', 13664168561, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (536, 'Monteros', 'Argentina', 'Carioca', 67284502180, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (850, 'Al Majāridah', 'Saudi Arabia', 'Village Green', 47305396880, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (156, 'Takefu', 'Japan', 'Eagan', 6334375229, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (728, 'Mayang', 'China', 'Charing Cross', 61764827905, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (512, 'Kanchanaburi', 'Thailand', 'Lillian', 87412628355, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (375, 'Cartagena', 'Philippines', 'Fairfield', 92350151960, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (188, 'Strogino', 'Russia', 'Butternut', 854496730, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (152, 'Dijon', 'France', 'Emmet', 11960494343, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (716, 'Tatrang', 'China', 'Northfield', 19996279949, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (991, 'Karlstad', 'Sweden', 'Manufacturers', 27268190933, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (571, 'Ekazhevo', 'Russia', 'Steensland', 88835479369, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (255, 'Kaeng Khro', 'Thailand', 'Cambridge', 51667749120, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (157, 'Tasböget', 'Kazakhstan', 'Schmedeman', 93951446053, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Kemil', 'Indonesia', 'Emmet', 40117232513, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (520, 'Sobrosa', 'Portugal', 'Claremont', 13012035625, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Coyaima', 'Colombia', 'Ruskin', 60901848349, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (586, 'Baltimore', 'United States', 'Meadow Vale', 51253991107, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (294, 'Dayton', 'United States', 'Marquette', 24958640873, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (942, 'Maracanaú', 'Brazil', 'Brown', 60278755463, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (369, 'Lingbei', 'China', 'Fulton', 73567832074, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (761, 'Xaçmaz', 'Azerbaijan', 'Brickson Park', 42332809836, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (217, 'Argostólion', 'Greece', 'Dovetail', 7923888087, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (54, 'Baiqi', 'China', 'Graceland', 41718559915, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (448, 'Huating', 'China', 'Goodland', 49142752351, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (193, 'Jaroměřice nad Rokytnou', 'Czech Republic', 'Carey', 5196487248, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (734, 'Bantuanon', 'Philippines', 'Duke', 14133816451, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (403, 'Paidha', 'Uganda', 'Calypso', 29712438028, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (439, 'Lundo', 'Indonesia', 'Cordelia', 84615207199, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (487, 'Seupakat', 'Indonesia', 'Veith', 14474570490, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (444, 'Kuloy', 'Russia', 'Express', 23547074511, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (651, 'Haysyn', 'Ukraine', 'Grover', 48275548617, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (643, 'Nozdrzec', 'Poland', 'Green Ridge', 76767291638, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (245, 'Caringin', 'Indonesia', 'Doe Crossing', 2875498801, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (798, 'Pasarbaru', 'Indonesia', 'Linden', 17694819681, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (890, 'Davila', 'Philippines', 'Harper', 41542540252, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (339, 'Tqibuli', 'Georgia', 'Helena', 96403425463, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (408, 'Sumbergebang', 'Indonesia', 'Surrey', 1417720585, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (437, 'Jadi', 'Indonesia', 'Merrick', 66721763218, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (926, 'Mekon', 'Indonesia', 'Dwight', 26297801377, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (751, 'Chaman', 'Pakistan', 'Declaration', 14652769342, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (368, 'Baihe', 'China', 'Straubel', 31675120522, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (143, 'Jiangchuanlu', 'China', 'Bonner', 11615358561, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (839, 'Bongandanga', 'Democratic Republic of the Congo', 'New Castle', 25733403741, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (750, 'Noemuti', 'Indonesia', 'Sloan', 25825270315, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (602, 'Koutsopódi', 'Greece', 'Memorial', 78860281793, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (371, 'Minneapolis', 'United States', 'Melody', 50448362933, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (459, 'Beiyang', 'China', 'Jackson', 81876635779, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (10, 'Dalong', 'China', 'Glacier Hill', 21131509478, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (573, 'Mozhong', 'China', 'Donald', 68357772707, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (213, 'Rybinsk', 'Russia', 'Hansons', 27766644207, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (706, 'Mayahi', 'Niger', 'Jenna', 2876053068, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (723, 'Sabana de Parra', 'Venezuela', 'Walton', 46790464807, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (9, 'Alcáçovas', 'Portugal', 'Packers', 49876127417, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (930, 'Murmuiža', 'Latvia', 'Victoria', 33522093718, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (888, 'Golema Rečica', 'Macedonia', 'Reinke', 5530433668, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (473, 'Tanahwulan', 'Indonesia', 'Hoepker', 11689940656, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (445, 'Sukahening', 'Indonesia', 'Anzinger', 98662883248, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (530, 'Jianyangping', 'China', 'Killdeer', 35322775344, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (994, 'Jeziora Wielkie', 'Poland', 'Stuart', 18727369552, 'Customer');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (363, 'Wendengying', 'China', 'Amoth', 39540527592, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (72, 'Ajax', 'Canada', 'Carioca', 55014770790, 'Driver');
insert into ADDRESS (zip_code, city, country, street, license_number, type) values (467, 'Angao', 'China', 'Merry', 7701984209, 'Customer');