insert into ACCIDENT (id, date, time, description) values (1205, '25-Feb-1998', '12:36 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (242, '07-Nov-1992', '7:27 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1056, '09-Mar-1955', '10:51 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6294, '27-Jun-1979', '6:25 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3596, '08-Jan-1981', '4:39 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (924, '01-Aug-1977', '2:57 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (38, '29-Sep-1967', '10:20 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8920, '14-Sep-1964', '8:36 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5845, '28-Mar-1970', '5:09 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6798, '12-Nov-1983', '1:38 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6165, '19-Mar-1987', '8:01 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (9695, '26-Mar-1983', '8:54 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3898, '04-Aug-1962', '8:04 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1221, '24-Feb-1977', '11:56 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3127, '12-Feb-1972', '1:21 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5258, '02-Sep-1988', '6:35 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (631, '03-Jun-1985', '7:12 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2471, '19-Dec-1984', '1:37 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2936, '03-Jun-1983', '3:09 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9029, '05-Dec-1984', '9:59 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5395, '06-Jun-1998', '12:22 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1476, '31-Mar-1990', '4:22 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3734, '05-Sep-1960', '7:03 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1269, '01-Feb-2001', '8:27 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5433, '24-Jun-1972', '6:39 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2024, '29-Jun-1994', '7:38 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3438, '12-Oct-1960', '4:28 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2642, '30-Nov-1976', '11:11 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8323, '27-Jun-1999', '10:51 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4124, '19-Nov-1986', '11:34 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4214, '21-Nov-1983', '5:33 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5344, '18-Apr-1990', '12:26 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3527, '20-Nov-1964', '10:29 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5763, '04-Aug-1966', '2:53 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1981, '29-Feb-1984', '2:27 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2266, '01-Jul-1997', '7:56 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5603, '07-Jun-1975', '1:27 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8221, '24-Feb-1989', '7:33 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4822, '23-Jan-1983', '1:54 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4182, '12-Apr-1956', '4:22 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1992, '28-Nov-1980', '4:09 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3469, '06-Jan-1994', '6:49 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (213, '23-Sep-1980', '1:40 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2434, '23-Jul-1990', '8:39 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5435, '31-Dec-1989', '11:56 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4177, '02-Dec-1996', '10:27 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2704, '19-May-1956', '3:11 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3001, '01-Oct-1984', '8:56 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9587, '27-May-1974', '8:45 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4150, '02-Feb-1966', '11:20 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5018, '10-Feb-1994', '10:16 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5526, '16-Aug-1984', '2:45 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (273, '31-Dec-1959', '1:13 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1073, '25-Sep-1974', '9:28 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5736, '05-Feb-1961', '7:43 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3661, '20-Mar-1994', '7:42 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7468, '22-Dec-1993', '4:54 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5207, '18-Jul-1990', '4:12 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2476, '25-Mar-1986', '11:52 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7866, '27-Dec-1989', '4:20 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1614, '12-Aug-1970', '8:59 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7903, '24-Dec-1985', '2:31 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8656, '11-Feb-1984', '9:19 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4108, '30-Apr-1958', '10:01 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6511, '13-Feb-1971', '1:48 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6685, '25-Sep-1956', '9:24 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2089, '04-Jun-1957', '12:04 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2543, '04-Feb-1977', '3:08 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4598, '01-Dec-1985', '11:58 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7520, '17-Jul-1983', '3:56 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8590, '21-Nov-1990', '8:33 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2327, '02-Nov-1959', '2:50 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2179, '16-Jun-1987', '12:57 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2268, '30-Nov-1984', '2:15 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6914, '23-Oct-1999', '2:22 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (9554, '04-Dec-1973', '7:45 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4991, '25-Jan-1959', '5:00 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7563, '23-Jan-1969', '2:55 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (363, '16-Aug-1962', '8:23 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7677, '10-Aug-1960', '8:16 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7451, '04-Feb-1985', '11:55 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4060, '15-Jul-1983', '2:36 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2441, '20-Feb-1973', '1:50 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2475, '12-Jun-1994', '6:25 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6889, '17-Oct-1957', '2:53 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4802, '26-Sep-1968', '3:50 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4659, '01-Apr-1969', '6:03 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6564, '10-May-1997', '9:02 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8345, '02-Oct-1959', '7:55 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3979, '02-Oct-1973', '7:00 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3890, '09-Jul-1960', '10:10 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (235, '05-Jun-1967', '8:42 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8782, '18-Dec-1968', '8:26 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4888, '14-Jan-1987', '9:05 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6336, '03-Jan-1965', '3:25 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2529, '08-May-1958', '5:33 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2135, '27-Mar-1969', '1:36 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7469, '05-Jul-1959', '7:40 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2687, '12-Jan-1979', '11:36 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6375, '01-Oct-1969', '9:17 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3108, '14-Jan-1992', '2:02 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2496, '28-Mar-1956', '2:39 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1604, '16-Sep-1980', '1:25 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3592, '02-Aug-1962', '4:47 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1022, '09-Jul-2001', '2:03 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (158, '18-Jun-1999', '6:09 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6218, '26-Oct-1990', '3:30 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2852, '12-Oct-1987', '1:24 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (155, '04-Oct-1981', '11:53 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7113, '24-Sep-1977', '9:06 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5398, '16-Nov-1968', '2:15 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7233, '17-Sep-1984', '11:13 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6074, '15-May-1971', '10:27 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1911, '26-May-1995', '2:34 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6894, '01-Jul-1972', '3:14 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8987, '13-Oct-1980', '1:24 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5859, '19-Feb-1980', '4:52 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8756, '17-Jun-1995', '8:43 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8935, '27-Jan-1981', '7:34 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9685, '06-Sep-1981', '6:13 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4697, '03-Sep-1986', '10:33 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4891, '28-Aug-1988', '5:30 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3570, '17-Sep-1982', '12:39 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6518, '23-Mar-1964', '2:44 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3372, '06-Dec-2001', '3:16 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (281, '28-Oct-1960', '9:56 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1773, '25-Dec-1997', '9:38 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6609, '01-Mar-2001', '2:26 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3366, '14-Feb-1981', '8:49 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4734, '08-Jul-1994', '10:33 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4261, '25-Aug-1955', '2:10 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5999, '06-Feb-1993', '8:22 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3940, '22-Aug-1959', '7:19 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7284, '01-Jan-1964', '1:48 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (609, '16-Feb-1990', '9:21 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2871, '25-Oct-1982', '5:22 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3328, '12-May-1969', '2:10 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8263, '04-Aug-1998', '7:28 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8530, '28-Jun-1988', '12:26 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1264, '02-Sep-1988', '7:15 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (919, '28-Apr-1958', '4:19 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2386, '08-Feb-1977', '12:00 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (9160, '18-Feb-1955', '7:59 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6845, '07-Jul-1965', '1:35 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6150, '16-Dec-1957', '3:00 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3368, '28-Sep-1973', '3:32 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1692, '06-Jul-1979', '9:47 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2447, '24-Mar-1975', '1:43 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1304, '04-Jul-1988', '1:15 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9665, '10-Oct-1974', '5:56 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8465, '23-Nov-1978', '8:11 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8025, '09-Sep-1964', '10:52 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7646, '28-Mar-1960', '3:32 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9761, '15-May-1983', '3:20 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2129, '08-Aug-1995', '8:07 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (529, '18-Sep-1976', '10:22 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5707, '16-Oct-1972', '11:53 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7750, '15-Jan-1973', '4:59 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9104, '15-Jul-1986', '1:05 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2794, '21-May-1990', '6:57 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8393, '21-Sep-1997', '9:54 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (507, '08-Jul-1997', '2:05 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6253, '25-Jan-1961', '6:08 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (660, '14-Nov-1988', '4:48 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3077, '26-Oct-1958', '1:00 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (412, '30-Mar-1970', '12:37 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5076, '14-Feb-1986', '1:45 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2104, '15-Jan-1968', '3:26 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8796, '15-Aug-1959', '10:17 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8829, '08-Sep-1965', '10:04 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1693, '17-Sep-1977', '12:09 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8466, '22-Dec-1965', '3:36 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6452, '26-Apr-1964', '10:17 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2367, '30-Jun-1965', '10:30 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6926, '15-Jan-1964', '5:21 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6212, '02-Apr-1955', '5:08 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5110, '08-Oct-1993', '4:07 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8145, '29-Sep-1969', '1:56 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8507, '07-Dec-1967', '8:14 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3493, '23-Mar-1955', '7:48 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4129, '03-Dec-1996', '2:48 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6429, '27-Oct-1997', '10:55 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4134, '22-Oct-1971', '2:54 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7965, '29-Jul-2001', '1:14 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2091, '23-Aug-1998', '1:03 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8855, '19-Jan-1996', '5:17 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (202, '23-Oct-1981', '5:25 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (656, '07-Sep-1966', '9:20 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7650, '07-Feb-1989', '1:14 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5970, '24-Apr-1979', '4:06 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6362, '17-Jul-1969', '8:21 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4747, '25-May-1965', '5:46 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5899, '13-Nov-1955', '7:41 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7487, '08-Oct-1981', '6:29 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3232, '09-Dec-1955', '5:05 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3968, '30-Dec-1976', '10:02 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4703, '12-Jun-1999', '7:35 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2928, '05-Sep-1972', '12:07 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (599, '16-Jun-1979', '10:53 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9817, '21-Aug-1983', '6:52 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6729, '13-Aug-1991', '7:33 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6634, '10-Oct-1968', '4:24 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1171, '12-Apr-1982', '4:11 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9583, '11-Aug-1983', '7:09 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8884, '06-May-1991', '4:54 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (232, '22-Feb-1989', '11:41 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3721, '06-Dec-1998', '10:54 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2402, '30-Nov-1975', '10:40 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8103, '31-Jul-1972', '6:48 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2424, '16-Jul-1998', '3:32 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7835, '22-Jul-2001', '5:04 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9892, '08-Oct-1974', '5:10 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2838, '19-Feb-1970', '9:41 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4580, '01-Jul-1977', '8:06 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (142, '20-Sep-1961', '1:12 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5079, '19-Mar-1979', '12:04 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5498, '21-Jun-1973', '4:00 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6012, '14-Nov-1983', '12:50 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8403, '25-Jun-1956', '4:13 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6810, '13-Feb-1987', '4:40 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4931, '04-Nov-1960', '11:20 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (41, '22-Feb-1964', '6:28 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4791, '23-Jul-1981', '8:05 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7221, '29-Sep-1987', '9:11 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2298, '08-Aug-1984', '10:26 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1040, '15-Oct-1962', '6:51 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (935, '07-Dec-1986', '8:02 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1584, '30-Dec-1972', '6:39 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (39, '21-Mar-1999', '12:35 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (283, '16-Nov-1990', '10:00 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5128, '30-Aug-1994', '3:57 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5722, '14-Jan-1970', '5:52 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1465, '30-Dec-1964', '5:46 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5077, '13-Jan-1972', '4:12 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2412, '22-Jan-1996', '11:28 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3699, '18-Feb-1970', '10:27 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7083, '08-Mar-1992', '1:29 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3531, '28-Sep-1996', '7:41 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9461, '13-Jan-2000', '4:08 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (122, '18-Dec-1987', '8:33 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5807, '22-Dec-1964', '2:08 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1364, '15-Jan-1981', '7:30 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5561, '07-Jan-1966', '12:20 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6302, '04-Jun-1997', '7:06 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7995, '10-Feb-1962', '8:53 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2380, '31-Dec-1960', '3:14 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7206, '15-Nov-1963', '1:58 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6766, '07-Jan-1979', '5:57 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6350, '10-Oct-1995', '7:17 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7004, '25-Jul-1993', '7:56 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8342, '15-Apr-1993', '1:55 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2660, '07-Aug-1956', '4:38 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2861, '06-Jun-1983', '5:07 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7771, '03-Jul-1984', '2:36 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6620, '08-Oct-1970', '6:21 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (966, '16-Sep-1999', '8:33 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7453, '28-Feb-1967', '10:10 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9722, '15-Jan-1971', '7:05 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4523, '07-Jan-1959', '3:31 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1462, '29-Apr-2000', '2:06 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9338, '31-Aug-1988', '3:58 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4638, '23-Jun-1968', '12:27 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2411, '21-Jun-1990', '3:11 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2835, '14-Jun-1958', '11:49 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3864, '09-Feb-1994', '4:01 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (13, '24-Sep-1956', '1:02 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (166, '12-Oct-1999', '10:28 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3270, '23-May-1992', '8:50 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3964, '10-Jul-1968', '6:31 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7329, '09-Nov-1973', '12:15 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6944, '30-Jan-1996', '5:24 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6800, '27-Apr-1992', '1:26 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3000, '10-Mar-1987', '11:58 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7793, '21-Oct-1978', '5:38 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3217, '18-Jan-1994', '10:45 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1659, '18-Jul-1989', '7:58 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1551, '03-Dec-1990', '3:37 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3488, '10-Jun-1977', '2:06 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6274, '02-Apr-1979', '9:31 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5309, '19-Oct-1958', '2:04 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6115, '30-Jan-1995', '3:15 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5768, '27-Feb-1988', '10:55 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3795, '16-Jun-1987', '10:51 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4925, '02-Jun-1988', '10:44 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2975, '06-Jul-1976', '1:47 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4965, '17-Oct-1982', '3:06 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4554, '18-May-1974', '9:57 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9048, '15-Mar-1977', '6:05 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8872, '18-Jan-2000', '5:20 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3032, '25-Mar-1958', '11:47 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3624, '25-May-1956', '7:19 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6357, '10-Jun-1999', '7:39 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9674, '14-Aug-1972', '8:58 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6667, '09-Aug-1964', '9:27 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7245, '19-Apr-1995', '8:10 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5935, '05-Dec-1962', '7:36 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2395, '29-Sep-1964', '8:27 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4932, '31-Jan-1981', '4:57 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7032, '10-Feb-1961', '10:58 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2889, '12-Feb-1963', '1:10 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6137, '27-Mar-1983', '2:28 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7184, '01-Dec-1975', '3:13 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1441, '25-Jul-1996', '10:37 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4372, '14-Feb-1958', '11:21 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4140, '18-May-1997', '6:40 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (209, '28-Nov-1966', '12:47 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1403, '02-Feb-1979', '7:11 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4178, '08-Dec-1955', '9:43 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9238, '22-Nov-1959', '6:23 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1897, '17-Mar-1971', '5:32 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2885, '05-May-2001', '9:00 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6040, '27-Mar-1963', '9:11 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (18, '26-Nov-1991', '7:06 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (749, '11-Mar-2001', '7:37 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9762, '27-Aug-1999', '7:38 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8599, '08-Sep-1984', '7:12 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (391, '14-Jan-1993', '7:23 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6565, '23-Apr-1974', '10:37 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2626, '05-May-1990', '12:30 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8462, '29-Apr-1969', '11:25 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5050, '16-Apr-1965', '10:16 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2609, '14-Mar-1997', '3:10 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2634, '06-Mar-1993', '1:28 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4039, '19-Apr-1971', '12:59 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2978, '29-Jun-1956', '9:13 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9344, '26-Dec-1961', '10:35 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8097, '24-Jan-1996', '4:55 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4629, '02-Oct-1999', '4:47 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3369, '09-Apr-1980', '8:43 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2066, '22-Feb-1965', '3:07 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5190, '17-Feb-1987', '7:21 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2351, '20-Dec-1956', '11:06 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4877, '22-Feb-1999', '7:53 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (120, '11-Oct-1971', '7:32 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1236, '26-Jul-2001', '6:21 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6724, '09-Jan-1994', '11:17 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5620, '25-Jul-1993', '6:12 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8618, '24-Aug-1966', '10:48 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9072, '21-Dec-1961', '3:22 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2553, '30-Apr-1981', '6:03 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2840, '13-Dec-1998', '9:38 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1338, '21-Nov-1988', '4:55 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6324, '06-Jun-1973', '1:51 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4350, '24-Jul-1982', '12:25 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4147, '12-Feb-1957', '6:47 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5553, '16-Dec-1960', '4:00 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9808, '12-Jun-1969', '11:11 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2308, '20-Feb-1955', '1:19 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5332, '07-Sep-1955', '5:09 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9058, '08-Apr-1974', '3:14 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6008, '06-Oct-1959', '5:55 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7237, '25-Jun-1965', '10:24 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2186, '25-Nov-1998', '10:25 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3307, '10-Feb-1963', '10:50 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6636, '11-Mar-1984', '9:14 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2159, '24-Nov-1996', '4:09 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2741, '13-Dec-1960', '11:08 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6955, '25-Jan-1984', '6:43 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2277, '26-Aug-1967', '8:02 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2783, '23-Jan-1980', '11:29 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3528, '03-Jun-1997', '7:42 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5185, '08-Dec-1957', '2:05 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (995, '18-Jul-1967', '3:26 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8095, '30-Jun-1963', '12:32 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9768, '14-Jan-1979', '9:59 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8848, '31-Jan-2001', '12:58 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (348, '01-Mar-1975', '12:25 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6643, '17-Jul-1962', '5:14 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4102, '13-Mar-1969', '11:09 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6791, '05-Jul-1987', '3:42 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1481, '13-Oct-1976', '3:06 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (4913, '03-Sep-2001', '7:26 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1395, '24-Feb-1956', '1:16 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4585, '25-Aug-1955', '7:13 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8310, '16-Nov-1999', '4:04 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (757, '21-Aug-1974', '2:56 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8707, '03-Sep-1993', '7:09 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (200, '06-Mar-1978', '8:52 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2951, '30-Jun-1999', '3:37 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (9283, '14-Apr-1964', '4:37 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7439, '28-Jul-1987', '12:42 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2385, '25-Apr-1980', '12:00 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2849, '09-Aug-1973', '5:28 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6908, '24-Mar-1967', '2:18 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7452, '27-Jun-1964', '1:23 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7672, '21-Jun-1985', '1:45 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4868, '19-Aug-1978', '8:35 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7687, '21-Jan-1972', '11:39 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4611, '14-Dec-1975', '9:09 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3432, '18-Nov-1977', '6:00 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5342, '01-Sep-1958', '1:12 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6900, '20-Apr-1957', '4:40 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8301, '26-Jun-1973', '12:37 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2549, '20-Jun-1992', '8:19 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3035, '05-Apr-1964', '5:47 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2810, '23-Mar-1973', '2:41 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (8509, '30-Apr-1960', '2:03 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7163, '27-Dec-1961', '4:50 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1214, '04-Aug-1956', '8:30 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2354, '12-Jan-1980', '4:43 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2258, '05-Mar-1993', '3:40 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4411, '23-Jul-1969', '10:20 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4679, '02-Oct-2000', '6:48 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3394, '11-Nov-1967', '9:57 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1959, '07-Dec-1970', '10:07 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3110, '15-Nov-1994', '6:32 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4986, '21-Aug-1994', '2:45 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9209, '28-Sep-1991', '11:58 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (461, '12-Dec-2000', '5:52 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8365, '15-Mar-1973', '8:14 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1176, '27-Feb-1984', '9:31 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5571, '01-Oct-1965', '3:11 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (8389, '08-Jun-1981', '2:04 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (88, '17-Oct-1964', '1:30 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8424, '16-May-1973', '4:43 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3330, '29-Jan-1958', '12:30 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7211, '05-Apr-1988', '7:42 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2405, '20-Dec-2001', '5:21 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1107, '16-Jul-1961', '3:51 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9466, '12-Mar-1989', '8:59 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5001, '22-May-1989', '3:54 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7643, '17-Feb-1992', '7:27 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (9573, '08-Feb-1997', '7:23 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (476, '30-Sep-1985', '4:41 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3130, '14-Dec-1975', '9:56 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (2730, '09-Sep-1956', '2:27 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (2318, '20-Oct-1961', '4:28 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (6552, '23-Jan-1957', '11:13 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1479, '20-Apr-1964', '1:40 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (7264, '11-Apr-1955', '1:45 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4640, '08-Jun-1955', '12:09 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3690, '05-Nov-1980', '5:27 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6403, '15-Dec-1957', '8:57 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9575, '04-Oct-1997', '1:43 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1991, '17-Jun-1968', '9:55 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2288, '06-Oct-1963', '8:41 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1918, '25-Sep-1969', '5:32 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (4823, '01-Sep-1990', '7:57 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3888, '25-Jan-1956', '6:34 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8467, '17-Oct-1990', '3:20 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5078, '15-Jun-1978', '11:53 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (1109, '28-Jul-1955', '7:20 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2691, '03-Sep-1968', '12:19 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5455, '29-Jun-1962', '9:13 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2175, '24-Mar-1964', '4:07 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8196, '07-Jun-1995', '6:25 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (9281, '09-Jun-1961', '4:16 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4680, '20-Jun-1955', '8:32 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9745, '28-Jun-1969', '8:25 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (7730, '26-Jul-1956', '4:17 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (3293, '27-Jan-1998', '8:08 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (9752, '27-Mar-1982', '12:46 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (90, '07-Apr-1993', '1:32 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4394, '03-Aug-1994', '11:08 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (275, '03-Mar-1962', '12:45 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3628, '04-Aug-1984', '9:34 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6038, '24-Nov-1983', '5:56 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (1457, '13-Feb-1982', '4:28 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (7384, '27-Jun-1988', '4:46 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (711, '29-Mar-1991', '5:17 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (6971, '05-Apr-1970', '10:18 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (6177, '16-Feb-1980', '1:08 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1696, '13-Jun-1985', '5:10 AM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (5179, '08-Dec-1980', '1:27 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3786, '15-Jan-1980', '8:50 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (3713, '04-Nov-1968', '2:41 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (5097, '18-Aug-1972', '9:52 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (874, '03-Jun-1994', '8:36 AM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (4583, '22-Nov-1966', '1:48 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (729, '28-Jul-1957', '2:21 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3068, '06-Mar-1980', '7:44 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (1126, '01-May-1977', '8:00 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (2180, '11-Oct-1955', '10:35 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5562, '06-Feb-1998', '6:34 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (5439, '29-Aug-1967', '2:57 PM', 'The other driver was looking at his phone');
insert into ACCIDENT (id, date, time, description) values (215, '16-Oct-1995', '7:39 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (2939, '07-Mar-1978', '10:53 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (505, '23-Dec-1960', '7:10 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (8859, '21-Jun-1970', '6:29 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (4198, '04-Dec-1957', '2:05 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (1087, '16-May-2000', '3:11 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (8313, '19-Jul-2001', '11:21 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (6642, '28-Oct-1983', '12:25 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (5440, '16-Dec-1995', '9:25 PM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (9231, '27-Mar-1993', '10:16 PM', 'The other driver passed a red light');
insert into ACCIDENT (id, date, time, description) values (3771, '17-Jul-1978', '7:18 AM', 'The other driver was coming from left and i was coming from right');
insert into ACCIDENT (id, date, time, description) values (7249, '29-Dec-1990', '11:54 PM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3634, '17-Jul-1998', '4:30 AM', 'The other driver left a stop sign without stopping');
insert into ACCIDENT (id, date, time, description) values (3444, '03-Apr-1958', '7:21 AM', 'The other driver left a stop sign without stopping');